(define (problem instance-6)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6)
  (:init
    (handempty)
    (ontable b4)
    (ontable b2)
    (ontable b6)
    (on b3 b2)
    (on b1 b3)
    (on b5 b4)
    (clear b6)
    (clear b1)
    (clear b5)
  )
  (:goal
    (and
      (on b1 b2)
      (on b2 b3)
      (on b3 b4)
      (on b4 b5)
      (on b5 b6)
    )
  )
)
