(define (problem instance-10)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10)
  (:init
    (handempty)
    (ontable b8)
    (ontable b3)
    (ontable b2)
    (ontable b9)
    (ontable b6)
    (ontable b7)
    (ontable b1)
    (on b5 b2)
    (on b4 b5)
    (on b10 b7)
    (clear b8)
    (clear b3)
    (clear b9)
    (clear b6)
    (clear b1)
    (clear b4)
    (clear b10)
  )
  (:goal
    (and
      (on b1 b2)
      (on b2 b3)
      (on b3 b4)
      (on b4 b5)
      (on b5 b6)
      (on b6 b7)
      (on b7 b8)
      (on b8 b9)
      (on b9 b10)
    )
  )
)
