(define (problem instance-9)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9)
  (:init
    (handempty)
    (ontable b4)
    (ontable b3)
    (ontable b7)
    (ontable b5)
    (ontable b1)
    (ontable b8)
    (ontable b6)
    (ontable b2)
    (on b9 b6)
    (clear b4)
    (clear b3)
    (clear b7)
    (clear b5)
    (clear b1)
    (clear b8)
    (clear b2)
    (clear b9)
  )
  (:goal
    (and
      (on b1 b2)
      (on b2 b3)
      (on b3 b4)
      (on b4 b5)
      (on b5 b6)
      (on b6 b7)
      (on b7 b8)
      (on b8 b9)
    )
  )
)
