(define (problem instance-9)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9)
  (:init
    (handempty)
    (ontable b3)
    (ontable b2)
    (ontable b7)
    (on b1 b7)
    (on b5 b2)
    (on b8 b5)
    (on b6 b1)
    (on b9 b6)
    (on b4 b9)
    (clear b3)
    (clear b8)
    (clear b4)
  )
  (:goal
    (and
      (on b1 b2)
      (on b2 b3)
      (on b3 b4)
      (on b4 b5)
      (on b5 b6)
      (on b6 b7)
      (on b7 b8)
      (on b8 b9)
    )
  )
)
