(define (problem instance-9)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9)
  (:init
    (handempty)
    (ontable b2)
    (ontable b3)
    (ontable b7)
    (ontable b5)
    (on b8 b3)
    (on b9 b5)
    (on b4 b7)
    (on b1 b4)
    (on b6 b2)
    (clear b8)
    (clear b9)
    (clear b1)
    (clear b6)
  )
  (:goal
    (and
      (on b1 b2)
      (on b2 b3)
      (on b3 b4)
      (on b4 b5)
      (on b5 b6)
      (on b6 b7)
      (on b7 b8)
      (on b8 b9)
    )
  )
)
