(define (problem instance-7)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7)
  (:init
    (handempty)
    (ontable b2)
    (ontable b3)
    (ontable b7)
    (on b6 b3)
    (on b4 b2)
    (on b1 b6)
    (on b5 b4)
    (clear b7)
    (clear b1)
    (clear b5)
  )
  (:goal
    (and
      (on b1 b2)
      (on b2 b3)
      (on b3 b4)
      (on b4 b5)
      (on b5 b6)
      (on b6 b7)
    )
  )
)
