(define (problem instance-8)
  (:domain blocksworld-4ops)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8)
  (:init
    (handempty)
    (on-table b4)
    (on-table b6)
    (on-table b2)
    (on b5 b4)
    (on b1 b4)
    (on b8 b1)
    (on b7 b2)
    (on b3 b5)
    (clear b6)
    (clear b4)
    (clear b8)
    (clear b2)
    (clear b7)
    (clear b3)
  )
  (:goal
    (and
      (on b1 b2)
      (on b2 b3)
      (on b3 b4)
      (on b4 b5)
      (on b5 b6)
      (on b6 b7)
      (on b7 b8)
    )
  )
)
