(define (problem instance-5)
  (:domain blocksworld-4ops)
  (:objects b1 b2 b3 b4 b5)
  (:init
    (handempty)
    (on-table b1)
    (on-table b4)
    (on b5 b1)
    (on b2 b5)
    (on b3 b1)
    (clear b1)
    (clear b3)
    (clear b4)
    (clear b2)
  )
  (:goal
    (and
      (on b1 b2)
      (on b2 b3)
      (on b3 b4)
      (on b4 b5)
    )
  )
)
