(define (problem instance-9)
  (:domain blocksworld-4ops)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9)
  (:init
    (handempty)
    (on-table b3)
    (on-table b2)
    (on-table b8)
    (on-table b9)
    (on b5 b3)
    (on b6 b3)
    (on b1 b5)
    (on b4 b1)
    (on b7 b5)
    (clear b6)
    (clear b4)
    (clear b8)
    (clear b9)
    (clear b2)
    (clear b7)
    (clear b3)
  )
  (:goal
    (and
      (on b1 b2)
      (on b2 b3)
      (on b3 b4)
      (on b4 b5)
      (on b5 b6)
      (on b6 b7)
      (on b7 b8)
      (on b8 b9)
    )
  )
)
