(define (problem instance-9)
  (:domain blocksworld-4ops)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9)
  (:init
    (handempty)
    (on-table b3)
    (on-table b7)
    (on b1 b3)
    (on b5 b1)
    (on b6 b5)
    (on b4 b7)
    (on b2 b7)
    (on b9 b5)
    (on b8 b6)
    (clear b3)
    (clear b4)
    (clear b9)
    (clear b8)
    (clear b2)
    (clear b7)
  )
  (:goal
    (and
      (on b1 b2)
      (on b2 b3)
      (on b3 b4)
      (on b4 b5)
      (on b5 b6)
      (on b6 b7)
      (on b7 b8)
      (on b8 b9)
    )
  )
)
