(define (problem instance-9)
  (:domain blocksworld-4ops)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9)
  (:init
    (handempty)
    (on-table b1)
    (on-table b3)
    (on b7 b1)
    (on b6 b1)
    (on b8 b7)
    (on b9 b7)
    (on b2 b1)
    (on b4 b1)
    (on b5 b8)
    (clear b6)
    (clear b4)
    (clear b1)
    (clear b9)
    (clear b2)
    (clear b5)
    (clear b3)
  )
  (:goal
    (and
      (on b1 b2)
      (on b2 b3)
      (on b3 b4)
      (on b4 b5)
      (on b5 b6)
      (on b6 b7)
      (on b7 b8)
      (on b8 b9)
    )
  )
)
