(define (problem instance-9)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9)
  (:init
    (handempty)
    (ontable b3)
    (ontable b9)
    (ontable b8)
    (on b1 b8)
    (on b4 b1)
    (on b5 b9)
    (on b7 b3)
    (on b6 b5)
    (on b2 b4)
    (clear b7)
    (clear b6)
    (clear b2)
  )
  (:goal
    (and
      (on b1 b2)
      (on b2 b3)
      (on b3 b4)
      (on b4 b5)
      (on b5 b6)
      (on b6 b7)
      (on b7 b8)
      (on b8 b9)
    )
  )
)
