(define (problem instance-8)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8)
  (:init
    (handempty)
    (ontable b7)
    (ontable b3)
    (ontable b2)
    (ontable b6)
    (on b8 b7)
    (on b4 b2)
    (on b5 b6)
    (on b1 b8)
    (clear b3)
    (clear b4)
    (clear b5)
    (clear b1)
  )
  (:goal
    (and
      (on b1 b2)
      (on b2 b3)
      (on b3 b4)
      (on b4 b5)
      (on b5 b6)
      (on b6 b7)
      (on b7 b8)
    )
  )
)
