(define (problem instance-6)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6)
  (:init
    (handempty)
    (ontable b1)
    (ontable b5)
    (ontable b2)
    (on b3 b5)
    (on b6 b2)
    (on b4 b6)
    (clear b1)
    (clear b3)
    (clear b4)
  )
  (:goal
    (and
      (on b1 b2)
      (on b2 b3)
      (on b3 b4)
      (on b4 b5)
      (on b5 b6)
    )
  )
)
