(define (problem instance-9)
  (:domain blocksworld-4ops)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9)
  (:init
    (handempty)
    (on-table b8)
    (on-table b9)
    (on-table b5)
    (on b3 b8)
    (on b6 b8)
    (on b7 b8)
    (on b1 b8)
    (on b2 b6)
    (on b4 b8)
    (clear b1)
    (clear b8)
    (clear b3)
    (clear b4)
    (clear b7)
    (clear b5)
    (clear b2)
    (clear b9)
  )
  (:goal
    (and
      (on b1 b2)
      (on b2 b3)
      (on b3 b4)
      (on b4 b5)
      (on b5 b6)
      (on b6 b7)
      (on b7 b8)
      (on b8 b9)
    )
  )
)
