(define (problem instance-10)
  (:domain blocksworld-4ops)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10)
  (:init
    (handempty)
    (on-table b7)
    (on-table b8)
    (on-table b10)
    (on-table b4)
    (on-table b5)
    (on-table b6)
    (on b9 b7)
    (on b2 b8)
    (on b3 b2)
    (on b1 b8)
    (clear b6)
    (clear b4)
    (clear b1)
    (clear b10)
    (clear b8)
    (clear b9)
    (clear b5)
    (clear b7)
    (clear b3)
  )
  (:goal
    (and
      (on b1 b2)
      (on b2 b3)
      (on b3 b4)
      (on b4 b5)
      (on b5 b6)
      (on b6 b7)
      (on b7 b8)
      (on b8 b9)
      (on b9 b10)
    )
  )
)
