(define (problem instance-4)
  (:domain blocksworld-4ops)
  (:objects b1 b2 b3 b4)
  (:init
    (handempty)
    (on-table b1)
    (on-table b3)
    (on-table b2)
    (on b4 b1)
    (clear b1)
    (clear b2)
    (clear b3)
    (clear b4)
  )
  (:goal
    (and
      (on b1 b2)
      (on b2 b3)
      (on b3 b4)
    )
  )
)
