(define (problem instance-9)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9)
  (:init
    (handempty)
    (ontable b2)
    (ontable b8)
    (ontable b5)
    (ontable b9)
    (ontable b6)
    (ontable b1)
    (on b4 b2)
    (on b3 b4)
    (on b7 b8)
    (clear b5)
    (clear b9)
    (clear b6)
    (clear b1)
    (clear b3)
    (clear b7)
  )
  (:goal
    (and
      (on b1 b2)
      (on b2 b3)
      (on b3 b4)
      (on b4 b5)
      (on b5 b6)
      (on b6 b7)
      (on b7 b8)
      (on b8 b9)
    )
  )
)
