(define (problem instance-5)
  (:domain blocksworld-4ops)
  (:objects b1 b2 b3 b4 b5)
  (:init
    (handempty)
    (on-table b2)
    (on-table b1)
    (on-table b3)
    (on-table b5)
    (on b4 b2)
    (clear b4)
    (clear b1)
    (clear b2)
    (clear b5)
    (clear b3)
  )
  (:goal
    (and
      (on b1 b2)
      (on b2 b3)
      (on b3 b4)
      (on b4 b5)
    )
  )
)
