(define (problem instance-8)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8)
  (:init
    (handempty)
    (ontable b1)
    (ontable b6)
    (ontable b2)
    (ontable b4)
    (ontable b3)
    (on b8 b6)
    (on b5 b4)
    (on b7 b3)
    (clear b1)
    (clear b2)
    (clear b8)
    (clear b5)
    (clear b7)
  )
  (:goal
    (and
      (on b1 b2)
      (on b2 b3)
      (on b3 b4)
      (on b4 b5)
      (on b5 b6)
      (on b6 b7)
      (on b7 b8)
    )
  )
)
