(define (problem instance-8)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8)
  (:init
    (handempty)
    (ontable b2)
    (ontable b3)
    (ontable b8)
    (ontable b4)
    (ontable b1)
    (on b6 b4)
    (on b5 b3)
    (on b7 b8)
    (clear b2)
    (clear b1)
    (clear b6)
    (clear b5)
    (clear b7)
  )
  (:goal
    (and
      (on b1 b2)
      (on b2 b3)
      (on b3 b4)
      (on b4 b5)
      (on b5 b6)
      (on b6 b7)
      (on b7 b8)
    )
  )
)
