(define (problem instance-6)
  (:domain blocksworld-4ops)
  (:objects b1 b2 b3 b4 b5 b6)
  (:init
    (handempty)
    (on-table b4)
    (on-table b5)
    (on-table b2)
    (on b1 b5)
    (on b6 b5)
    (on b3 b2)
    (clear b1)
    (clear b3)
    (clear b4)
    (clear b6)
    (clear b5)
    (clear b2)
  )
  (:goal
    (and
      (on b1 b2)
      (on b2 b3)
      (on b3 b4)
      (on b4 b5)
      (on b5 b6)
    )
  )
)
