(define (problem instance-10)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10)
  (:init
    (handempty)
    (ontable b7)
    (ontable b1)
    (ontable b4)
    (ontable b9)
    (ontable b5)
    (on b3 b7)
    (on b2 b4)
    (on b10 b2)
    (on b8 b9)
    (on b6 b5)
    (clear b1)
    (clear b3)
    (clear b10)
    (clear b8)
    (clear b6)
  )
  (:goal
    (and
      (on b1 b9)
    )
  )
)
