(define (problem instance-11)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10 b11)
  (:init
    (handempty)
    (ontable b2)
    (ontable b3)
    (ontable b11)
    (ontable b5)
    (ontable b8)
    (ontable b9)
    (ontable b4)
    (ontable b7)
    (on b10 b11)
    (on b1 b9)
    (on b6 b4)
    (clear b2)
    (clear b3)
    (clear b5)
    (clear b8)
    (clear b7)
    (clear b10)
    (clear b1)
    (clear b6)
  )
  (:goal
    (and
      (on b6 b8)
    )
  )
)
