(define (problem instance-9)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9)
  (:init
    (handempty)
    (ontable b4)
    (ontable b5)
    (ontable b2)
    (ontable b6)
    (on b9 b2)
    (on b1 b9)
    (on b8 b5)
    (on b3 b1)
    (on b7 b3)
    (clear b4)
    (clear b6)
    (clear b8)
    (clear b7)
  )
  (:goal
    (and
      (on b6 b4)
    )
  )
)
