(define (problem instance-9)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9)
  (:init
    (handempty)
    (ontable b2)
    (ontable b1)
    (ontable b4)
    (ontable b8)
    (ontable b3)
    (ontable b9)
    (on b6 b8)
    (on b7 b1)
    (on b5 b9)
    (clear b2)
    (clear b4)
    (clear b3)
    (clear b6)
    (clear b7)
    (clear b5)
  )
  (:goal
    (and
      (on b4 b5)
    )
  )
)
