(define (problem instance-10)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10)
  (:init
    (handempty)
    (ontable b7)
    (ontable b2)
    (ontable b1)
    (ontable b8)
    (ontable b9)
    (ontable b6)
    (ontable b5)
    (on b10 b5)
    (on b3 b2)
    (on b4 b9)
    (clear b7)
    (clear b1)
    (clear b8)
    (clear b6)
    (clear b10)
    (clear b3)
    (clear b4)
  )
  (:goal
    (and
      (on b10 b6)
    )
  )
)
