(define (problem instance-10)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10)
  (:init
    (handempty)
    (ontable b1)
    (ontable b4)
    (ontable b8)
    (ontable b7)
    (ontable b9)
    (on b3 b9)
    (on b6 b7)
    (on b2 b6)
    (on b10 b2)
    (on b5 b10)
    (clear b1)
    (clear b4)
    (clear b8)
    (clear b3)
    (clear b5)
  )
  (:goal
    (and
      (on b3 b2)
    )
  )
)
