(define (problem instance-8)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8)
  (:init
    (handempty)
    (ontable b6)
    (ontable b8)
    (ontable b4)
    (ontable b2)
    (ontable b1)
    (on b7 b4)
    (on b3 b6)
    (on b5 b7)
    (clear b8)
    (clear b2)
    (clear b1)
    (clear b3)
    (clear b5)
  )
  (:goal
    (and
      (on b6 b4)
    )
  )
)
