(define (problem instance-9)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9)
  (:init
    (handempty)
    (ontable b4)
    (ontable b8)
    (ontable b2)
    (on b1 b8)
    (on b3 b1)
    (on b7 b4)
    (on b6 b7)
    (on b9 b6)
    (on b5 b2)
    (clear b3)
    (clear b9)
    (clear b5)
  )
  (:goal
    (and
      (on b3 b4)
    )
  )
)
