(define (problem instance-10)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10)
  (:init
    (handempty)
    (ontable b1)
    (ontable b9)
    (ontable b10)
    (on b6 b10)
    (on b3 b6)
    (on b8 b3)
    (on b4 b8)
    (on b7 b1)
    (on b5 b9)
    (on b2 b4)
    (clear b7)
    (clear b5)
    (clear b2)
  )
  (:goal
    (and
      (on b6 b5)
    )
  )
)
