(define (problem instance-10)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10)
  (:init
    (handempty)
    (ontable b10)
    (ontable b3)
    (ontable b5)
    (on b2 b10)
    (on b7 b2)
    (on b6 b5)
    (on b9 b3)
    (on b1 b7)
    (on b4 b1)
    (on b8 b9)
    (clear b6)
    (clear b4)
    (clear b8)
  )
  (:goal
    (and
      (on b9 b1)
    )
  )
)
