(define (problem instance-13)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10 b11 b12 b13)
  (:init
    (handempty)
    (ontable b8)
    (ontable b13)
    (ontable b11)
    (ontable b7)
    (ontable b1)
    (ontable b4)
    (ontable b6)
    (ontable b9)
    (ontable b10)
    (ontable b12)
    (ontable b5)
    (ontable b2)
    (on b3 b10)
    (clear b8)
    (clear b13)
    (clear b11)
    (clear b7)
    (clear b1)
    (clear b4)
    (clear b6)
    (clear b9)
    (clear b12)
    (clear b5)
    (clear b2)
    (clear b3)
  )
  (:goal
    (and
      (on b5 b11)
    )
  )
)
