(define (problem instance-13)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10 b11 b12 b13)
  (:init
    (handempty)
    (ontable b10)
    (ontable b3)
    (ontable b8)
    (ontable b12)
    (ontable b11)
    (ontable b13)
    (ontable b6)
    (ontable b2)
    (ontable b1)
    (ontable b9)
    (on b4 b1)
    (on b5 b6)
    (on b7 b2)
    (clear b10)
    (clear b3)
    (clear b8)
    (clear b12)
    (clear b11)
    (clear b13)
    (clear b9)
    (clear b4)
    (clear b5)
    (clear b7)
  )
  (:goal
    (and
      (on b5 b3)
    )
  )
)
