(define (problem instance-12)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10 b11 b12)
  (:init
    (handempty)
    (ontable b9)
    (ontable b12)
    (ontable b8)
    (ontable b5)
    (ontable b7)
    (ontable b1)
    (ontable b6)
    (ontable b3)
    (ontable b4)
    (ontable b2)
    (on b11 b3)
    (on b10 b12)
    (clear b9)
    (clear b8)
    (clear b5)
    (clear b7)
    (clear b1)
    (clear b6)
    (clear b4)
    (clear b2)
    (clear b11)
    (clear b10)
  )
  (:goal
    (and
      (on b9 b2)
    )
  )
)
