(define (problem instance-9)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9)
  (:init
    (handempty)
    (ontable b1)
    (ontable b8)
    (ontable b5)
    (ontable b9)
    (ontable b4)
    (ontable b6)
    (on b3 b9)
    (on b2 b8)
    (on b7 b5)
    (clear b1)
    (clear b4)
    (clear b6)
    (clear b3)
    (clear b2)
    (clear b7)
  )
  (:goal
    (and
      (on b5 b1)
    )
  )
)
