(define (problem instance-9)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9)
  (:init
    (handempty)
    (ontable b6)
    (ontable b1)
    (ontable b4)
    (on b8 b1)
    (on b3 b6)
    (on b5 b4)
    (on b7 b3)
    (on b9 b7)
    (on b2 b8)
    (clear b5)
    (clear b9)
    (clear b2)
  )
  (:goal
    (and
      (on b2 b9)
    )
  )
)
