(define (problem instance-9)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9)
  (:init
    (handempty)
    (ontable b8)
    (ontable b3)
    (ontable b4)
    (on b7 b4)
    (on b6 b7)
    (on b2 b6)
    (on b1 b3)
    (on b5 b1)
    (on b9 b8)
    (clear b2)
    (clear b5)
    (clear b9)
  )
  (:goal
    (and
      (on b6 b1)
    )
  )
)
