(define (problem instance-12)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10 b11 b12)
  (:init
    (handempty)
    (ontable b1)
    (ontable b10)
    (ontable b7)
    (ontable b3)
    (ontable b2)
    (ontable b8)
    (ontable b11)
    (ontable b9)
    (on b5 b7)
    (on b4 b3)
    (on b12 b4)
    (on b6 b9)
    (clear b1)
    (clear b10)
    (clear b2)
    (clear b8)
    (clear b11)
    (clear b5)
    (clear b12)
    (clear b6)
  )
  (:goal
    (and
      (on b7 b9)
    )
  )
)
