(define (problem instance-11)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10 b11)
  (:init
    (handempty)
    (ontable b3)
    (ontable b7)
    (ontable b9)
    (ontable b8)
    (ontable b2)
    (ontable b11)
    (on b6 b3)
    (on b10 b11)
    (on b4 b7)
    (on b5 b9)
    (on b1 b5)
    (clear b8)
    (clear b2)
    (clear b6)
    (clear b10)
    (clear b4)
    (clear b1)
  )
  (:goal
    (and
      (on b10 b6)
    )
  )
)
