(define (problem instance-9)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9)
  (:init
    (handempty)
    (ontable b3)
    (ontable b7)
    (ontable b6)
    (ontable b4)
    (on b2 b4)
    (on b1 b3)
    (on b9 b2)
    (on b8 b6)
    (on b5 b1)
    (clear b7)
    (clear b9)
    (clear b8)
    (clear b5)
  )
  (:goal
    (and
      (on b3 b7)
    )
  )
)
