(define (problem instance-9)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9)
  (:init
    (handempty)
    (ontable b5)
    (ontable b9)
    (ontable b1)
    (ontable b8)
    (ontable b7)
    (ontable b4)
    (on b3 b1)
    (on b2 b7)
    (on b6 b4)
    (clear b5)
    (clear b9)
    (clear b8)
    (clear b3)
    (clear b2)
    (clear b6)
  )
  (:goal
    (and
      (on b7 b2)
    )
  )
)
