(define (problem instance-11)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10 b11)
  (:init
    (handempty)
    (ontable b2)
    (ontable b11)
    (ontable b5)
    (ontable b3)
    (ontable b10)
    (ontable b6)
    (ontable b4)
    (ontable b8)
    (on b7 b3)
    (on b9 b2)
    (on b1 b8)
    (clear b11)
    (clear b5)
    (clear b10)
    (clear b6)
    (clear b4)
    (clear b7)
    (clear b9)
    (clear b1)
  )
  (:goal
    (and
      (on b8 b3)
    )
  )
)
