(define (problem instance-10)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10)
  (:init
    (handempty)
    (ontable b3)
    (ontable b2)
    (ontable b6)
    (ontable b1)
    (ontable b9)
    (ontable b7)
    (ontable b8)
    (on b4 b8)
    (on b10 b1)
    (on b5 b3)
    (clear b2)
    (clear b6)
    (clear b9)
    (clear b7)
    (clear b4)
    (clear b10)
    (clear b5)
  )
  (:goal
    (and
      (on b8 b10)
    )
  )
)
