(define (problem instance-11)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10 b11)
  (:init
    (handempty)
    (ontable b11)
    (ontable b7)
    (ontable b4)
    (ontable b8)
    (ontable b3)
    (ontable b10)
    (ontable b1)
    (ontable b9)
    (on b5 b8)
    (on b2 b3)
    (on b6 b7)
    (clear b11)
    (clear b4)
    (clear b10)
    (clear b1)
    (clear b9)
    (clear b5)
    (clear b2)
    (clear b6)
  )
  (:goal
    (and
      (on b8 b4)
    )
  )
)
