(define (problem instance-9)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9)
  (:init
    (handempty)
    (ontable b4)
    (ontable b6)
    (ontable b7)
    (ontable b8)
    (on b2 b8)
    (on b3 b2)
    (on b9 b4)
    (on b1 b7)
    (on b5 b3)
    (clear b6)
    (clear b9)
    (clear b1)
    (clear b5)
  )
  (:goal
    (and
      (on b1 b2)
    )
  )
)
