(define (problem instance-9)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9)
  (:init
    (handempty)
    (ontable b5)
    (ontable b9)
    (ontable b7)
    (ontable b6)
    (ontable b1)
    (on b8 b1)
    (on b4 b6)
    (on b2 b5)
    (on b3 b7)
    (clear b9)
    (clear b8)
    (clear b4)
    (clear b2)
    (clear b3)
  )
  (:goal
    (and
      (on b1 b9)
    )
  )
)
