(define (problem instance-11)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10 b11)
  (:init
    (handempty)
    (ontable b4)
    (ontable b10)
    (ontable b7)
    (ontable b11)
    (ontable b2)
    (ontable b5)
    (ontable b9)
    (ontable b8)
    (on b3 b8)
    (on b6 b2)
    (on b1 b10)
    (clear b4)
    (clear b7)
    (clear b11)
    (clear b5)
    (clear b9)
    (clear b3)
    (clear b6)
    (clear b1)
  )
  (:goal
    (and
      (on b3 b7)
    )
  )
)
