(define (problem instance-10)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10)
  (:init
    (handempty)
    (ontable b6)
    (ontable b9)
    (ontable b10)
    (ontable b3)
    (ontable b5)
    (on b1 b6)
    (on b8 b3)
    (on b4 b10)
    (on b2 b4)
    (on b7 b5)
    (clear b9)
    (clear b1)
    (clear b8)
    (clear b2)
    (clear b7)
  )
  (:goal
    (and
      (on b6 b8)
    )
  )
)
