(define (problem instance-9)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9)
  (:init
    (handempty)
    (ontable b7)
    (ontable b6)
    (ontable b3)
    (on b2 b3)
    (on b5 b7)
    (on b9 b2)
    (on b4 b5)
    (on b8 b6)
    (on b1 b9)
    (clear b4)
    (clear b8)
    (clear b1)
  )
  (:goal
    (and
      (on b1 b7)
    )
  )
)
