(define (problem instance-10)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10)
  (:init
    (handempty)
    (ontable b8)
    (ontable b6)
    (ontable b2)
    (ontable b10)
    (ontable b9)
    (on b3 b2)
    (on b7 b6)
    (on b1 b8)
    (on b4 b9)
    (on b5 b7)
    (clear b10)
    (clear b3)
    (clear b1)
    (clear b4)
    (clear b5)
  )
  (:goal
    (and
      (on b7 b1)
    )
  )
)
