(define (problem instance-12)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10 b11 b12)
  (:init
    (handempty)
    (ontable b6)
    (ontable b9)
    (ontable b8)
    (ontable b11)
    (ontable b2)
    (ontable b5)
    (ontable b3)
    (ontable b10)
    (on b12 b3)
    (on b1 b2)
    (on b7 b12)
    (on b4 b9)
    (clear b6)
    (clear b8)
    (clear b11)
    (clear b5)
    (clear b10)
    (clear b1)
    (clear b7)
    (clear b4)
  )
  (:goal
    (and
      (on b4 b12)
    )
  )
)
