(define (problem instance-12)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10 b11 b12)
  (:init
    (handempty)
    (ontable b3)
    (ontable b1)
    (ontable b2)
    (ontable b10)
    (ontable b4)
    (ontable b8)
    (ontable b12)
    (ontable b6)
    (ontable b5)
    (on b11 b12)
    (on b7 b3)
    (on b9 b5)
    (clear b1)
    (clear b2)
    (clear b10)
    (clear b4)
    (clear b8)
    (clear b6)
    (clear b11)
    (clear b7)
    (clear b9)
  )
  (:goal
    (and
      (on b10 b8)
    )
  )
)
