(define (problem instance-8)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8)
  (:init
    (handempty)
    (ontable b1)
    (ontable b2)
    (ontable b3)
    (ontable b4)
    (ontable b6)
    (on b8 b4)
    (on b7 b2)
    (on b5 b8)
    (clear b1)
    (clear b3)
    (clear b6)
    (clear b7)
    (clear b5)
  )
  (:goal
    (and
      (on b5 b3)
    )
  )
)
