(define (problem instance-10)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10)
  (:init
    (handempty)
    (ontable b10)
    (ontable b8)
    (ontable b4)
    (ontable b6)
    (ontable b9)
    (ontable b7)
    (on b5 b8)
    (on b2 b9)
    (on b3 b2)
    (on b1 b10)
    (clear b4)
    (clear b6)
    (clear b7)
    (clear b5)
    (clear b3)
    (clear b1)
  )
  (:goal
    (and
      (on b8 b1)
    )
  )
)
