(define (problem instance-12)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10 b11 b12)
  (:init
    (handempty)
    (ontable b8)
    (ontable b10)
    (ontable b6)
    (ontable b4)
    (ontable b2)
    (ontable b1)
    (ontable b5)
    (ontable b9)
    (ontable b11)
    (ontable b3)
    (ontable b7)
    (on b12 b9)
    (clear b8)
    (clear b10)
    (clear b6)
    (clear b4)
    (clear b2)
    (clear b1)
    (clear b5)
    (clear b11)
    (clear b3)
    (clear b7)
    (clear b12)
  )
  (:goal
    (and
      (on b10 b7)
    )
  )
)
