(define (problem instance-7)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7)
  (:init
    (handempty)
    (ontable b1)
    (ontable b2)
    (ontable b7)
    (ontable b5)
    (ontable b4)
    (ontable b6)
    (ontable b3)
    (clear b1)
    (clear b2)
    (clear b7)
    (clear b5)
    (clear b4)
    (clear b6)
    (clear b3)
  )
  (:goal
    (and
      (on b5 b1)
    )
  )
)
