(define (problem instance-9)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9)
  (:init
    (handempty)
    (ontable b9)
    (ontable b3)
    (ontable b6)
    (ontable b7)
    (on b8 b6)
    (on b1 b9)
    (on b2 b3)
    (on b5 b2)
    (on b4 b7)
    (clear b8)
    (clear b1)
    (clear b5)
    (clear b4)
  )
  (:goal
    (and
      (on b2 b8)
    )
  )
)
