(define (problem instance-11)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10 b11)
  (:init
    (handempty)
    (ontable b1)
    (ontable b8)
    (ontable b4)
    (ontable b3)
    (ontable b2)
    (ontable b10)
    (on b5 b2)
    (on b6 b1)
    (on b11 b3)
    (on b9 b4)
    (on b7 b5)
    (clear b8)
    (clear b10)
    (clear b6)
    (clear b11)
    (clear b9)
    (clear b7)
  )
  (:goal
    (and
      (on b8 b6)
    )
  )
)
