(define (problem instance-12)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10 b11 b12)
  (:init
    (handempty)
    (ontable b5)
    (ontable b10)
    (ontable b6)
    (ontable b4)
    (ontable b9)
    (ontable b8)
    (ontable b1)
    (ontable b11)
    (on b7 b1)
    (on b2 b8)
    (on b12 b5)
    (on b3 b9)
    (clear b10)
    (clear b6)
    (clear b4)
    (clear b11)
    (clear b7)
    (clear b2)
    (clear b12)
    (clear b3)
  )
  (:goal
    (and
      (on b5 b10)
    )
  )
)
