(define (problem instance-11)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10 b11)
  (:init
    (handempty)
    (ontable b9)
    (ontable b7)
    (ontable b3)
    (ontable b1)
    (ontable b5)
    (ontable b8)
    (ontable b2)
    (ontable b6)
    (ontable b10)
    (on b11 b10)
    (on b4 b3)
    (clear b9)
    (clear b7)
    (clear b1)
    (clear b5)
    (clear b8)
    (clear b2)
    (clear b6)
    (clear b11)
    (clear b4)
  )
  (:goal
    (and
      (on b11 b1)
    )
  )
)
