(define (problem instance-10)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10)
  (:init
    (handempty)
    (ontable b3)
    (ontable b9)
    (ontable b6)
    (ontable b5)
    (ontable b7)
    (ontable b1)
    (ontable b10)
    (on b2 b6)
    (on b8 b10)
    (on b4 b9)
    (clear b3)
    (clear b5)
    (clear b7)
    (clear b1)
    (clear b2)
    (clear b8)
    (clear b4)
  )
  (:goal
    (and
      (on b1 b5)
    )
  )
)
