(define (problem instance-10)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10)
  (:init
    (handempty)
    (ontable b3)
    (ontable b2)
    (ontable b10)
    (ontable b8)
    (on b9 b2)
    (on b4 b3)
    (on b6 b4)
    (on b1 b9)
    (on b7 b10)
    (on b5 b1)
    (clear b8)
    (clear b6)
    (clear b7)
    (clear b5)
  )
  (:goal
    (and
      (on b3 b5)
    )
  )
)
