(define (problem instance-11)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10 b11)
  (:init
    (handempty)
    (ontable b9)
    (ontable b4)
    (ontable b5)
    (ontable b7)
    (ontable b11)
    (ontable b8)
    (ontable b3)
    (ontable b10)
    (on b1 b5)
    (on b2 b1)
    (on b6 b3)
    (clear b9)
    (clear b4)
    (clear b7)
    (clear b11)
    (clear b8)
    (clear b10)
    (clear b2)
    (clear b6)
  )
  (:goal
    (and
      (on b7 b2)
    )
  )
)
