(define (problem instance-12)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10 b11 b12)
  (:init
    (handempty)
    (ontable b1)
    (ontable b9)
    (ontable b5)
    (ontable b4)
    (ontable b3)
    (ontable b8)
    (ontable b12)
    (ontable b6)
    (on b2 b8)
    (on b10 b4)
    (on b7 b6)
    (on b11 b7)
    (clear b1)
    (clear b9)
    (clear b5)
    (clear b3)
    (clear b12)
    (clear b2)
    (clear b10)
    (clear b11)
  )
  (:goal
    (and
      (on b8 b10)
    )
  )
)
