(define (problem instance-9)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9)
  (:init
    (handempty)
    (ontable b1)
    (ontable b9)
    (ontable b5)
    (on b4 b5)
    (on b3 b9)
    (on b8 b4)
    (on b6 b8)
    (on b2 b1)
    (on b7 b2)
    (clear b3)
    (clear b6)
    (clear b7)
  )
  (:goal
    (and
      (on b9 b6)
    )
  )
)
