(define (problem instance-11)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10 b11)
  (:init
    (handempty)
    (ontable b5)
    (ontable b6)
    (ontable b3)
    (ontable b8)
    (ontable b1)
    (ontable b7)
    (ontable b11)
    (ontable b10)
    (on b2 b8)
    (on b9 b10)
    (on b4 b7)
    (clear b5)
    (clear b6)
    (clear b3)
    (clear b1)
    (clear b11)
    (clear b2)
    (clear b9)
    (clear b4)
  )
  (:goal
    (and
      (on b4 b1)
    )
  )
)
