(define (problem instance-9)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9)
  (:init
    (handempty)
    (ontable b5)
    (ontable b6)
    (ontable b2)
    (ontable b7)
    (on b3 b6)
    (on b1 b3)
    (on b8 b7)
    (on b9 b5)
    (on b4 b1)
    (clear b2)
    (clear b8)
    (clear b9)
    (clear b4)
  )
  (:goal
    (and
      (on b2 b9)
    )
  )
)
