(define (problem instance-10)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10)
  (:init
    (handempty)
    (ontable b9)
    (ontable b8)
    (ontable b10)
    (ontable b3)
    (ontable b6)
    (ontable b1)
    (on b5 b1)
    (on b2 b9)
    (on b7 b10)
    (on b4 b6)
    (clear b8)
    (clear b3)
    (clear b5)
    (clear b2)
    (clear b7)
    (clear b4)
  )
  (:goal
    (and
      (on b1 b10)
    )
  )
)
