(define (problem instance-10)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10)
  (:init
    (handempty)
    (ontable b4)
    (ontable b5)
    (ontable b8)
    (ontable b7)
    (ontable b6)
    (ontable b3)
    (ontable b10)
    (on b2 b8)
    (on b1 b10)
    (on b9 b2)
    (clear b4)
    (clear b5)
    (clear b7)
    (clear b6)
    (clear b3)
    (clear b1)
    (clear b9)
  )
  (:goal
    (and
      (on b6 b4)
    )
  )
)
