(define (problem instance-10)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10)
  (:init
    (handempty)
    (ontable b2)
    (ontable b3)
    (ontable b1)
    (ontable b8)
    (ontable b6)
    (ontable b10)
    (ontable b4)
    (on b7 b10)
    (on b9 b7)
    (on b5 b2)
    (clear b3)
    (clear b1)
    (clear b8)
    (clear b6)
    (clear b4)
    (clear b9)
    (clear b5)
  )
  (:goal
    (and
      (on b10 b5)
    )
  )
)
