(define (problem instance-11)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10 b11)
  (:init
    (handempty)
    (ontable b10)
    (ontable b8)
    (ontable b2)
    (ontable b3)
    (ontable b5)
    (ontable b6)
    (ontable b11)
    (ontable b7)
    (on b1 b8)
    (on b4 b6)
    (on b9 b5)
    (clear b10)
    (clear b2)
    (clear b3)
    (clear b11)
    (clear b7)
    (clear b1)
    (clear b4)
    (clear b9)
  )
  (:goal
    (and
      (on b5 b3)
    )
  )
)
