(define (problem instance-10)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10)
  (:init
    (handempty)
    (ontable b10)
    (ontable b3)
    (ontable b8)
    (ontable b7)
    (ontable b1)
    (ontable b4)
    (on b6 b8)
    (on b5 b4)
    (on b2 b3)
    (on b9 b5)
    (clear b10)
    (clear b7)
    (clear b1)
    (clear b6)
    (clear b2)
    (clear b9)
  )
  (:goal
    (and
      (on b9 b4)
    )
  )
)
