(define (problem instance-10)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10)
  (:init
    (handempty)
    (ontable b1)
    (ontable b8)
    (ontable b9)
    (ontable b10)
    (ontable b3)
    (ontable b5)
    (ontable b6)
    (on b4 b9)
    (on b2 b5)
    (on b7 b3)
    (clear b1)
    (clear b8)
    (clear b10)
    (clear b6)
    (clear b4)
    (clear b2)
    (clear b7)
  )
  (:goal
    (and
      (on b6 b7)
    )
  )
)
