(define (problem instance-9)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9)
  (:init
    (handempty)
    (ontable b4)
    (ontable b9)
    (ontable b5)
    (ontable b2)
    (ontable b7)
    (on b8 b5)
    (on b1 b2)
    (on b6 b7)
    (on b3 b6)
    (clear b4)
    (clear b9)
    (clear b8)
    (clear b1)
    (clear b3)
  )
  (:goal
    (and
      (on b2 b6)
    )
  )
)
