(define (problem instance-9)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9)
  (:init
    (handempty)
    (ontable b6)
    (ontable b1)
    (ontable b7)
    (ontable b2)
    (ontable b8)
    (ontable b4)
    (ontable b5)
    (ontable b9)
    (on b3 b6)
    (clear b1)
    (clear b7)
    (clear b2)
    (clear b8)
    (clear b4)
    (clear b5)
    (clear b9)
    (clear b3)
  )
  (:goal
    (and
      (on b9 b7)
    )
  )
)
