(define (problem instance-13)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10 b11 b12 b13)
  (:init
    (handempty)
    (ontable b13)
    (ontable b4)
    (ontable b8)
    (ontable b7)
    (ontable b5)
    (ontable b2)
    (ontable b10)
    (ontable b6)
    (ontable b3)
    (ontable b9)
    (ontable b12)
    (on b1 b8)
    (on b11 b10)
    (clear b13)
    (clear b4)
    (clear b7)
    (clear b5)
    (clear b2)
    (clear b6)
    (clear b3)
    (clear b9)
    (clear b12)
    (clear b1)
    (clear b11)
  )
  (:goal
    (and
      (on b9 b3)
    )
  )
)
