(define (problem instance-8)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8)
  (:init
    (handempty)
    (ontable b5)
    (ontable b1)
    (ontable b8)
    (ontable b3)
    (ontable b6)
    (ontable b7)
    (ontable b4)
    (on b2 b1)
    (clear b5)
    (clear b8)
    (clear b3)
    (clear b6)
    (clear b7)
    (clear b4)
    (clear b2)
  )
  (:goal
    (and
      (on b4 b6)
    )
  )
)
