(define (problem instance-9)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9)
  (:init
    (handempty)
    (ontable b9)
    (ontable b8)
    (ontable b3)
    (ontable b5)
    (ontable b1)
    (ontable b2)
    (on b4 b1)
    (on b6 b3)
    (on b7 b2)
    (clear b9)
    (clear b8)
    (clear b5)
    (clear b4)
    (clear b6)
    (clear b7)
  )
  (:goal
    (and
      (on b9 b4)
    )
  )
)
