(define (problem instance-10)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10)
  (:init
    (handempty)
    (ontable b3)
    (ontable b7)
    (ontable b10)
    (ontable b9)
    (ontable b4)
    (ontable b8)
    (on b2 b10)
    (on b1 b9)
    (on b6 b7)
    (on b5 b1)
    (clear b3)
    (clear b4)
    (clear b8)
    (clear b2)
    (clear b6)
    (clear b5)
  )
  (:goal
    (and
      (on b6 b4)
    )
  )
)
