(define (problem instance-10)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10)
  (:init
    (handempty)
    (ontable b5)
    (ontable b9)
    (ontable b6)
    (ontable b2)
    (on b1 b5)
    (on b3 b6)
    (on b10 b1)
    (on b4 b10)
    (on b8 b3)
    (on b7 b8)
    (clear b9)
    (clear b2)
    (clear b4)
    (clear b7)
  )
  (:goal
    (and
      (on b3 b8)
    )
  )
)
