(define (problem instance-10)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10)
  (:init
    (handempty)
    (ontable b10)
    (ontable b2)
    (ontable b8)
    (ontable b6)
    (on b4 b2)
    (on b5 b8)
    (on b9 b6)
    (on b3 b10)
    (on b1 b5)
    (on b7 b1)
    (clear b4)
    (clear b9)
    (clear b3)
    (clear b7)
  )
  (:goal
    (and
      (on b10 b9)
    )
  )
)
