(define (problem instance-12)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10 b11 b12)
  (:init
    (handempty)
    (ontable b9)
    (ontable b11)
    (ontable b2)
    (ontable b5)
    (ontable b8)
    (ontable b3)
    (ontable b7)
    (ontable b1)
    (ontable b12)
    (on b4 b9)
    (on b10 b12)
    (on b6 b8)
    (clear b11)
    (clear b2)
    (clear b5)
    (clear b3)
    (clear b7)
    (clear b1)
    (clear b4)
    (clear b10)
    (clear b6)
  )
  (:goal
    (and
      (on b8 b7)
    )
  )
)
