(define (problem instance-13)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10 b11 b12 b13)
  (:init
    (handempty)
    (ontable b6)
    (ontable b12)
    (ontable b7)
    (ontable b4)
    (ontable b8)
    (ontable b2)
    (ontable b3)
    (ontable b13)
    (ontable b10)
    (ontable b11)
    (ontable b1)
    (on b5 b8)
    (on b9 b12)
    (clear b6)
    (clear b7)
    (clear b4)
    (clear b2)
    (clear b3)
    (clear b13)
    (clear b10)
    (clear b11)
    (clear b1)
    (clear b5)
    (clear b9)
  )
  (:goal
    (and
      (on b11 b6)
    )
  )
)
