(define (problem instance-10)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10)
  (:init
    (handempty)
    (ontable b9)
    (ontable b2)
    (ontable b10)
    (ontable b1)
    (ontable b5)
    (on b3 b10)
    (on b8 b1)
    (on b4 b5)
    (on b6 b4)
    (on b7 b8)
    (clear b9)
    (clear b2)
    (clear b3)
    (clear b6)
    (clear b7)
  )
  (:goal
    (and
      (on b2 b4)
    )
  )
)
