(define (problem instance-12)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10 b11 b12)
  (:init
    (handempty)
    (ontable b11)
    (ontable b8)
    (ontable b3)
    (ontable b5)
    (ontable b12)
    (ontable b6)
    (ontable b7)
    (ontable b4)
    (ontable b10)
    (on b2 b6)
    (on b1 b7)
    (on b9 b11)
    (clear b8)
    (clear b3)
    (clear b5)
    (clear b12)
    (clear b4)
    (clear b10)
    (clear b2)
    (clear b1)
    (clear b9)
  )
  (:goal
    (and
      (on b8 b4)
    )
  )
)
