(define (problem instance-13)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10 b11 b12 b13)
  (:init
    (handempty)
    (ontable b13)
    (ontable b2)
    (ontable b1)
    (ontable b12)
    (ontable b11)
    (ontable b8)
    (ontable b3)
    (ontable b10)
    (ontable b4)
    (ontable b9)
    (on b5 b12)
    (on b7 b11)
    (on b6 b1)
    (clear b13)
    (clear b2)
    (clear b8)
    (clear b3)
    (clear b10)
    (clear b4)
    (clear b9)
    (clear b5)
    (clear b7)
    (clear b6)
  )
  (:goal
    (and
      (on b2 b1)
    )
  )
)
