(define (problem instance-8)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8)
  (:init
    (handempty)
    (ontable b6)
    (ontable b8)
    (ontable b7)
    (ontable b4)
    (ontable b5)
    (on b2 b7)
    (on b1 b5)
    (on b3 b1)
    (clear b6)
    (clear b8)
    (clear b4)
    (clear b2)
    (clear b3)
  )
  (:goal
    (and
      (on b5 b8)
    )
  )
)
