(define (problem instance-11)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10 b11)
  (:init
    (handempty)
    (ontable b6)
    (ontable b2)
    (ontable b8)
    (ontable b5)
    (ontable b7)
    (ontable b4)
    (ontable b9)
    (on b11 b6)
    (on b1 b2)
    (on b10 b4)
    (on b3 b5)
    (clear b8)
    (clear b7)
    (clear b9)
    (clear b11)
    (clear b1)
    (clear b10)
    (clear b3)
  )
  (:goal
    (and
      (on b2 b11)
    )
  )
)
