(define (problem instance-10)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10)
  (:init
    (handempty)
    (ontable b1)
    (ontable b7)
    (ontable b3)
    (ontable b10)
    (ontable b2)
    (ontable b4)
    (ontable b5)
    (on b6 b4)
    (on b8 b10)
    (on b9 b1)
    (clear b7)
    (clear b3)
    (clear b2)
    (clear b5)
    (clear b6)
    (clear b8)
    (clear b9)
  )
  (:goal
    (and
      (on b3 b6)
    )
  )
)
