(define (problem instance-10)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10)
  (:init
    (handempty)
    (ontable b8)
    (ontable b6)
    (ontable b2)
    (ontable b3)
    (on b4 b8)
    (on b10 b6)
    (on b9 b2)
    (on b7 b4)
    (on b1 b7)
    (on b5 b9)
    (clear b3)
    (clear b10)
    (clear b1)
    (clear b5)
  )
  (:goal
    (and
      (on b3 b1)
    )
  )
)
