(define (problem instance-10)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10)
  (:init
    (handempty)
    (ontable b4)
    (ontable b1)
    (ontable b10)
    (ontable b8)
    (ontable b6)
    (ontable b3)
    (ontable b5)
    (on b7 b4)
    (on b2 b6)
    (on b9 b1)
    (clear b10)
    (clear b8)
    (clear b3)
    (clear b5)
    (clear b7)
    (clear b2)
    (clear b9)
  )
  (:goal
    (and
      (on b7 b9)
    )
  )
)
