(define (problem instance-10)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10)
  (:init
    (handempty)
    (ontable b5)
    (ontable b7)
    (ontable b4)
    (ontable b9)
    (on b6 b4)
    (on b3 b5)
    (on b1 b7)
    (on b2 b3)
    (on b8 b6)
    (on b10 b9)
    (clear b1)
    (clear b2)
    (clear b8)
    (clear b10)
  )
  (:goal
    (and
      (on b6 b10)
    )
  )
)
