(define (problem instance-10)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10)
  (:init
    (handempty)
    (ontable b4)
    (ontable b3)
    (ontable b8)
    (ontable b7)
    (ontable b5)
    (ontable b10)
    (on b9 b8)
    (on b1 b7)
    (on b2 b9)
    (on b6 b10)
    (clear b4)
    (clear b3)
    (clear b5)
    (clear b1)
    (clear b2)
    (clear b6)
  )
  (:goal
    (and
      (on b9 b6)
    )
  )
)
