(define (problem instance-12)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10 b11 b12)
  (:init
    (handempty)
    (ontable b10)
    (ontable b6)
    (ontable b7)
    (ontable b9)
    (ontable b11)
    (ontable b8)
    (ontable b3)
    (ontable b4)
    (on b5 b11)
    (on b1 b6)
    (on b12 b7)
    (on b2 b1)
    (clear b10)
    (clear b9)
    (clear b8)
    (clear b3)
    (clear b4)
    (clear b5)
    (clear b12)
    (clear b2)
  )
  (:goal
    (and
      (on b6 b11)
    )
  )
)
