(define (problem instance-11)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10 b11)
  (:init
    (handempty)
    (ontable b5)
    (ontable b2)
    (ontable b3)
    (ontable b4)
    (ontable b10)
    (ontable b9)
    (on b1 b9)
    (on b11 b10)
    (on b7 b4)
    (on b8 b1)
    (on b6 b2)
    (clear b5)
    (clear b3)
    (clear b11)
    (clear b7)
    (clear b8)
    (clear b6)
  )
  (:goal
    (and
      (on b8 b5)
    )
  )
)
