(define (problem instance-11)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10 b11)
  (:init
    (handempty)
    (ontable b6)
    (ontable b9)
    (ontable b1)
    (ontable b10)
    (ontable b11)
    (ontable b4)
    (ontable b7)
    (on b5 b11)
    (on b2 b9)
    (on b3 b2)
    (on b8 b4)
    (clear b6)
    (clear b1)
    (clear b10)
    (clear b7)
    (clear b5)
    (clear b3)
    (clear b8)
  )
  (:goal
    (and
      (on b7 b1)
    )
  )
)
