(define (problem instance-10)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10)
  (:init
    (handempty)
    (ontable b6)
    (ontable b3)
    (ontable b2)
    (ontable b9)
    (on b4 b9)
    (on b1 b2)
    (on b5 b1)
    (on b7 b4)
    (on b8 b7)
    (on b10 b5)
    (clear b6)
    (clear b3)
    (clear b8)
    (clear b10)
  )
  (:goal
    (and
      (on b2 b10)
    )
  )
)
