(define (problem instance-9)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9)
  (:init
    (handempty)
    (ontable b4)
    (ontable b7)
    (ontable b1)
    (on b9 b1)
    (on b6 b7)
    (on b2 b6)
    (on b3 b4)
    (on b8 b2)
    (on b5 b8)
    (clear b9)
    (clear b3)
    (clear b5)
  )
  (:goal
    (and
      (on b7 b9)
    )
  )
)
