(define (problem instance-12)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10 b11 b12)
  (:init
    (handempty)
    (ontable b1)
    (ontable b11)
    (ontable b5)
    (ontable b2)
    (ontable b4)
    (ontable b6)
    (ontable b12)
    (ontable b3)
    (on b10 b12)
    (on b8 b10)
    (on b9 b8)
    (on b7 b9)
    (clear b1)
    (clear b11)
    (clear b5)
    (clear b2)
    (clear b4)
    (clear b6)
    (clear b3)
    (clear b7)
  )
  (:goal
    (and
      (on b12 b7)
    )
  )
)
