(define (problem instance-10)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10)
  (:init
    (handempty)
    (ontable b1)
    (ontable b4)
    (ontable b5)
    (ontable b2)
    (ontable b9)
    (ontable b7)
    (on b6 b2)
    (on b8 b9)
    (on b3 b1)
    (on b10 b6)
    (clear b4)
    (clear b5)
    (clear b7)
    (clear b8)
    (clear b3)
    (clear b10)
  )
  (:goal
    (and
      (on b7 b10)
    )
  )
)
