(define (problem instance-10)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10)
  (:init
    (handempty)
    (ontable b8)
    (ontable b4)
    (ontable b6)
    (on b3 b4)
    (on b1 b8)
    (on b5 b1)
    (on b2 b5)
    (on b9 b6)
    (on b10 b2)
    (on b7 b9)
    (clear b3)
    (clear b10)
    (clear b7)
  )
  (:goal
    (and
      (on b1 b4)
    )
  )
)
