(define (problem instance-9)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9)
  (:init
    (handempty)
    (ontable b1)
    (ontable b5)
    (ontable b6)
    (ontable b9)
    (ontable b8)
    (ontable b3)
    (ontable b2)
    (on b7 b1)
    (on b4 b5)
    (clear b6)
    (clear b9)
    (clear b8)
    (clear b3)
    (clear b2)
    (clear b7)
    (clear b4)
  )
  (:goal
    (and
      (on b5 b6)
    )
  )
)
