(define (problem instance-9)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9)
  (:init
    (handempty)
    (ontable b7)
    (ontable b6)
    (ontable b8)
    (ontable b3)
    (ontable b5)
    (ontable b4)
    (on b1 b3)
    (on b9 b6)
    (on b2 b9)
    (clear b7)
    (clear b8)
    (clear b5)
    (clear b4)
    (clear b1)
    (clear b2)
  )
  (:goal
    (and
      (on b7 b8)
    )
  )
)
