(define (problem instance-10)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10)
  (:init
    (handempty)
    (ontable b3)
    (ontable b5)
    (ontable b6)
    (ontable b8)
    (ontable b9)
    (on b10 b8)
    (on b4 b10)
    (on b7 b3)
    (on b1 b5)
    (on b2 b1)
    (clear b6)
    (clear b9)
    (clear b4)
    (clear b7)
    (clear b2)
  )
  (:goal
    (and
      (on b6 b1)
    )
  )
)
