(define (problem instance-9)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9)
  (:init
    (handempty)
    (ontable b6)
    (ontable b5)
    (ontable b1)
    (on b2 b1)
    (on b9 b5)
    (on b7 b2)
    (on b8 b7)
    (on b3 b9)
    (on b4 b3)
    (clear b6)
    (clear b8)
    (clear b4)
  )
  (:goal
    (and
      (on b5 b6)
    )
  )
)
