(define (problem instance-10)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10)
  (:init
    (handempty)
    (ontable b7)
    (ontable b2)
    (ontable b10)
    (ontable b1)
    (ontable b5)
    (on b9 b2)
    (on b6 b5)
    (on b3 b6)
    (on b8 b7)
    (on b4 b8)
    (clear b10)
    (clear b1)
    (clear b9)
    (clear b3)
    (clear b4)
  )
  (:goal
    (and
      (on b1 b8)
    )
  )
)
