(define (problem instance-11)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10 b11)
  (:init
    (handempty)
    (ontable b11)
    (ontable b3)
    (ontable b5)
    (ontable b8)
    (ontable b6)
    (ontable b9)
    (ontable b2)
    (on b4 b11)
    (on b7 b4)
    (on b10 b8)
    (on b1 b7)
    (clear b3)
    (clear b5)
    (clear b6)
    (clear b9)
    (clear b2)
    (clear b10)
    (clear b1)
  )
  (:goal
    (and
      (on b10 b5)
    )
  )
)
