(define (problem instance-10)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10)
  (:init
    (handempty)
    (ontable b9)
    (ontable b8)
    (ontable b3)
    (ontable b5)
    (ontable b10)
    (on b2 b8)
    (on b6 b3)
    (on b4 b5)
    (on b7 b2)
    (on b1 b4)
    (clear b9)
    (clear b10)
    (clear b6)
    (clear b7)
    (clear b1)
  )
  (:goal
    (and
      (on b4 b8)
    )
  )
)
