(define (problem instance-12)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10 b11 b12)
  (:init
    (handempty)
    (ontable b9)
    (ontable b10)
    (ontable b3)
    (ontable b4)
    (ontable b11)
    (ontable b6)
    (ontable b5)
    (ontable b8)
    (ontable b7)
    (on b1 b5)
    (on b2 b3)
    (on b12 b9)
    (clear b10)
    (clear b4)
    (clear b11)
    (clear b6)
    (clear b8)
    (clear b7)
    (clear b1)
    (clear b2)
    (clear b12)
  )
  (:goal
    (and
      (on b1 b11)
    )
  )
)
