(define (problem instance-9)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9)
  (:init
    (handempty)
    (ontable b9)
    (ontable b2)
    (ontable b5)
    (ontable b8)
    (ontable b1)
    (on b4 b2)
    (on b7 b9)
    (on b6 b4)
    (on b3 b5)
    (clear b8)
    (clear b1)
    (clear b7)
    (clear b6)
    (clear b3)
  )
  (:goal
    (and
      (on b1 b3)
    )
  )
)
