(define (problem instance-10)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10)
  (:init
    (handempty)
    (ontable b2)
    (ontable b8)
    (ontable b3)
    (ontable b7)
    (ontable b6)
    (ontable b4)
    (on b1 b4)
    (on b10 b1)
    (on b5 b3)
    (on b9 b7)
    (clear b2)
    (clear b8)
    (clear b6)
    (clear b10)
    (clear b5)
    (clear b9)
  )
  (:goal
    (and
      (on b9 b8)
    )
  )
)
