(define (problem instance-8)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8)
  (:init
    (handempty)
    (ontable b7)
    (ontable b2)
    (ontable b3)
    (ontable b5)
    (ontable b6)
    (on b8 b6)
    (on b1 b8)
    (on b4 b3)
    (clear b7)
    (clear b2)
    (clear b5)
    (clear b1)
    (clear b4)
  )
  (:goal
    (and
      (on b5 b8)
    )
  )
)
