(define (problem instance-9)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9)
  (:init
    (handempty)
    (ontable b8)
    (ontable b6)
    (ontable b1)
    (ontable b9)
    (ontable b3)
    (on b2 b1)
    (on b5 b2)
    (on b7 b9)
    (on b4 b7)
    (clear b8)
    (clear b6)
    (clear b3)
    (clear b5)
    (clear b4)
  )
  (:goal
    (and
      (on b8 b7)
    )
  )
)
