(define (problem instance-9)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9)
  (:init
    (handempty)
    (ontable b9)
    (ontable b6)
    (ontable b7)
    (ontable b4)
    (ontable b2)
    (on b5 b4)
    (on b8 b6)
    (on b1 b7)
    (on b3 b8)
    (clear b9)
    (clear b2)
    (clear b5)
    (clear b1)
    (clear b3)
  )
  (:goal
    (and
      (on b3 b5)
    )
  )
)
