(define (problem instance-9)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9)
  (:init
    (handempty)
    (ontable b7)
    (ontable b8)
    (ontable b4)
    (ontable b5)
    (on b2 b4)
    (on b3 b7)
    (on b1 b2)
    (on b6 b5)
    (on b9 b1)
    (clear b8)
    (clear b3)
    (clear b6)
    (clear b9)
  )
  (:goal
    (and
      (on b7 b1)
    )
  )
)
