(define (problem instance-9)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9)
  (:init
    (handempty)
    (ontable b3)
    (ontable b7)
    (ontable b4)
    (ontable b5)
    (ontable b2)
    (ontable b9)
    (ontable b1)
    (on b8 b9)
    (on b6 b2)
    (clear b3)
    (clear b7)
    (clear b4)
    (clear b5)
    (clear b1)
    (clear b8)
    (clear b6)
  )
  (:goal
    (and
      (on b2 b3)
    )
  )
)
