(define (problem instance-8)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8)
  (:init
    (handempty)
    (ontable b4)
    (ontable b3)
    (ontable b5)
    (ontable b2)
    (ontable b6)
    (ontable b1)
    (on b7 b4)
    (on b8 b7)
    (clear b3)
    (clear b5)
    (clear b2)
    (clear b6)
    (clear b1)
    (clear b8)
  )
  (:goal
    (and
      (on b7 b3)
    )
  )
)
