(define (problem instance-9)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9)
  (:init
    (handempty)
    (ontable b1)
    (ontable b7)
    (ontable b9)
    (on b5 b9)
    (on b3 b5)
    (on b4 b7)
    (on b8 b4)
    (on b2 b1)
    (on b6 b8)
    (clear b3)
    (clear b2)
    (clear b6)
  )
  (:goal
    (and
      (on b1 b6)
    )
  )
)
