(define (problem instance-11)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10 b11)
  (:init
    (handempty)
    (ontable b5)
    (ontable b1)
    (ontable b6)
    (ontable b2)
    (ontable b11)
    (ontable b10)
    (ontable b4)
    (ontable b3)
    (on b7 b11)
    (on b8 b10)
    (on b9 b4)
    (clear b5)
    (clear b1)
    (clear b6)
    (clear b2)
    (clear b3)
    (clear b7)
    (clear b8)
    (clear b9)
  )
  (:goal
    (and
      (on b9 b1)
    )
  )
)
