(define (problem instance-9)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9)
  (:init
    (handempty)
    (ontable b5)
    (ontable b8)
    (ontable b6)
    (ontable b1)
    (ontable b3)
    (on b4 b8)
    (on b2 b3)
    (on b7 b4)
    (on b9 b7)
    (clear b5)
    (clear b6)
    (clear b1)
    (clear b2)
    (clear b9)
  )
  (:goal
    (and
      (on b9 b2)
    )
  )
)
