(define (problem instance-9)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9)
  (:init
    (handempty)
    (ontable b8)
    (ontable b2)
    (ontable b7)
    (ontable b1)
    (ontable b4)
    (on b9 b7)
    (on b3 b9)
    (on b6 b1)
    (on b5 b2)
    (clear b8)
    (clear b4)
    (clear b3)
    (clear b6)
    (clear b5)
  )
  (:goal
    (and
      (on b7 b5)
    )
  )
)
