(define (problem instance-10)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10)
  (:init
    (handempty)
    (ontable b4)
    (ontable b3)
    (ontable b7)
    (on b9 b7)
    (on b8 b9)
    (on b2 b4)
    (on b5 b8)
    (on b6 b2)
    (on b1 b5)
    (on b10 b1)
    (clear b3)
    (clear b6)
    (clear b10)
  )
  (:goal
    (and
      (on b3 b6)
    )
  )
)
