(define (problem instance-9)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9)
  (:init
    (handempty)
    (ontable b8)
    (ontable b2)
    (ontable b4)
    (on b3 b4)
    (on b5 b8)
    (on b9 b2)
    (on b6 b9)
    (on b1 b6)
    (on b7 b3)
    (clear b5)
    (clear b1)
    (clear b7)
  )
  (:goal
    (and
      (on b4 b5)
    )
  )
)
