(define (problem instance-11)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10 b11)
  (:init
    (handempty)
    (ontable b6)
    (ontable b8)
    (ontable b11)
    (ontable b10)
    (ontable b3)
    (ontable b9)
    (ontable b5)
    (on b2 b11)
    (on b1 b6)
    (on b7 b5)
    (on b4 b1)
    (clear b8)
    (clear b10)
    (clear b3)
    (clear b9)
    (clear b2)
    (clear b7)
    (clear b4)
  )
  (:goal
    (and
      (on b1 b9)
    )
  )
)
