(define (problem instance-13)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10 b11 b12 b13)
  (:init
    (handempty)
    (ontable b9)
    (ontable b12)
    (ontable b6)
    (ontable b2)
    (ontable b10)
    (ontable b1)
    (ontable b11)
    (ontable b5)
    (ontable b13)
    (ontable b3)
    (ontable b7)
    (on b8 b11)
    (on b4 b1)
    (clear b9)
    (clear b12)
    (clear b6)
    (clear b2)
    (clear b10)
    (clear b5)
    (clear b13)
    (clear b3)
    (clear b7)
    (clear b8)
    (clear b4)
  )
  (:goal
    (and
      (on b11 b13)
    )
  )
)
