(define (problem instance-11)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10 b11)
  (:init
    (handempty)
    (ontable b4)
    (ontable b9)
    (ontable b5)
    (ontable b6)
    (ontable b3)
    (ontable b10)
    (on b11 b6)
    (on b1 b9)
    (on b7 b5)
    (on b8 b10)
    (on b2 b7)
    (clear b4)
    (clear b3)
    (clear b11)
    (clear b1)
    (clear b8)
    (clear b2)
  )
  (:goal
    (and
      (on b1 b2)
    )
  )
)
