(define (problem instance-11)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10 b11)
  (:init
    (handempty)
    (ontable b1)
    (ontable b8)
    (ontable b10)
    (ontable b7)
    (ontable b5)
    (ontable b9)
    (ontable b4)
    (on b6 b8)
    (on b11 b6)
    (on b3 b5)
    (on b2 b7)
    (clear b1)
    (clear b10)
    (clear b9)
    (clear b4)
    (clear b11)
    (clear b3)
    (clear b2)
  )
  (:goal
    (and
      (on b4 b9)
    )
  )
)
