(define (problem instance-14)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10 b11 b12 b13 b14)
  (:init
    (handempty)
    (ontable b1)
    (ontable b7)
    (ontable b8)
    (ontable b6)
    (ontable b12)
    (ontable b10)
    (ontable b13)
    (ontable b11)
    (ontable b5)
    (ontable b9)
    (ontable b4)
    (ontable b14)
    (ontable b2)
    (ontable b3)
    (clear b1)
    (clear b7)
    (clear b8)
    (clear b6)
    (clear b12)
    (clear b10)
    (clear b13)
    (clear b11)
    (clear b5)
    (clear b9)
    (clear b4)
    (clear b14)
    (clear b2)
    (clear b3)
  )
  (:goal
    (and
      (on b7 b11)
    )
  )
)
