(define (problem instance-9)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9)
  (:init
    (handempty)
    (ontable b9)
    (ontable b1)
    (ontable b7)
    (ontable b5)
    (ontable b8)
    (ontable b4)
    (ontable b3)
    (ontable b6)
    (on b2 b4)
    (clear b9)
    (clear b1)
    (clear b7)
    (clear b5)
    (clear b8)
    (clear b3)
    (clear b6)
    (clear b2)
  )
  (:goal
    (and
      (on b7 b3)
    )
  )
)
