(define (problem instance-11)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10 b11)
  (:init
    (handempty)
    (ontable b9)
    (ontable b8)
    (ontable b7)
    (ontable b1)
    (ontable b4)
    (ontable b2)
    (ontable b10)
    (on b6 b7)
    (on b5 b4)
    (on b11 b10)
    (on b3 b2)
    (clear b9)
    (clear b8)
    (clear b1)
    (clear b6)
    (clear b5)
    (clear b11)
    (clear b3)
  )
  (:goal
    (and
      (on b5 b8)
    )
  )
)
