(define (problem instance-10)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10)
  (:init
    (handempty)
    (ontable b2)
    (ontable b6)
    (ontable b1)
    (ontable b7)
    (ontable b5)
    (on b10 b7)
    (on b4 b10)
    (on b3 b4)
    (on b9 b1)
    (on b8 b5)
    (clear b2)
    (clear b6)
    (clear b3)
    (clear b9)
    (clear b8)
  )
  (:goal
    (and
      (on b1 b6)
    )
  )
)
