(define (problem instance-10)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10)
  (:init
    (handempty)
    (ontable b5)
    (ontable b7)
    (ontable b10)
    (ontable b1)
    (ontable b6)
    (ontable b8)
    (ontable b9)
    (on b2 b1)
    (on b3 b8)
    (on b4 b10)
    (clear b5)
    (clear b7)
    (clear b6)
    (clear b9)
    (clear b2)
    (clear b3)
    (clear b4)
  )
  (:goal
    (and
      (on b1 b7)
    )
  )
)
