(define (problem instance-9)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9)
  (:init
    (handempty)
    (ontable b2)
    (ontable b7)
    (ontable b3)
    (on b1 b2)
    (on b4 b1)
    (on b6 b7)
    (on b5 b4)
    (on b8 b6)
    (on b9 b3)
    (clear b5)
    (clear b8)
    (clear b9)
  )
  (:goal
    (and
      (on b8 b5)
    )
  )
)
