(define (problem instance-11)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10 b11)
  (:init
    (handempty)
    (ontable b10)
    (ontable b4)
    (ontable b9)
    (ontable b5)
    (ontable b8)
    (ontable b2)
    (on b6 b9)
    (on b3 b5)
    (on b11 b8)
    (on b1 b4)
    (on b7 b3)
    (clear b10)
    (clear b2)
    (clear b6)
    (clear b11)
    (clear b1)
    (clear b7)
  )
  (:goal
    (and
      (on b1 b7)
    )
  )
)
