(define (problem instance-8)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8)
  (:init
    (handempty)
    (ontable b3)
    (ontable b5)
    (ontable b8)
    (ontable b2)
    (ontable b1)
    (ontable b4)
    (ontable b7)
    (on b6 b2)
    (clear b3)
    (clear b5)
    (clear b8)
    (clear b1)
    (clear b4)
    (clear b7)
    (clear b6)
  )
  (:goal
    (and
      (on b7 b2)
    )
  )
)
