(define (problem instance-10)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10)
  (:init
    (handempty)
    (ontable b1)
    (ontable b4)
    (ontable b3)
    (on b6 b3)
    (on b10 b6)
    (on b9 b4)
    (on b7 b1)
    (on b8 b9)
    (on b5 b8)
    (on b2 b5)
    (clear b10)
    (clear b7)
    (clear b2)
  )
  (:goal
    (and
      (on b7 b4)
    )
  )
)
