(define (problem instance-13)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10 b11 b12 b13)
  (:init
    (handempty)
    (ontable b12)
    (ontable b13)
    (ontable b11)
    (ontable b8)
    (ontable b4)
    (ontable b10)
    (ontable b2)
    (ontable b3)
    (ontable b1)
    (ontable b9)
    (on b5 b10)
    (on b6 b4)
    (on b7 b6)
    (clear b12)
    (clear b13)
    (clear b11)
    (clear b8)
    (clear b2)
    (clear b3)
    (clear b1)
    (clear b9)
    (clear b5)
    (clear b7)
  )
  (:goal
    (and
      (on b4 b6)
    )
  )
)
