(define (problem instance-8)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8)
  (:init
    (handempty)
    (ontable b2)
    (ontable b4)
    (ontable b3)
    (ontable b8)
    (ontable b6)
    (ontable b1)
    (on b5 b2)
    (on b7 b1)
    (clear b4)
    (clear b3)
    (clear b8)
    (clear b6)
    (clear b5)
    (clear b7)
  )
  (:goal
    (and
      (on b2 b7)
    )
  )
)
