(define (problem instance-9)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9)
  (:init
    (handempty)
    (ontable b6)
    (ontable b3)
    (ontable b7)
    (ontable b1)
    (ontable b9)
    (ontable b8)
    (on b4 b1)
    (on b5 b3)
    (on b2 b9)
    (clear b6)
    (clear b7)
    (clear b8)
    (clear b4)
    (clear b5)
    (clear b2)
  )
  (:goal
    (and
      (on b1 b5)
    )
  )
)
