(define (problem instance-10)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10)
  (:init
    (handempty)
    (ontable b1)
    (ontable b9)
    (ontable b6)
    (ontable b3)
    (on b7 b1)
    (on b4 b7)
    (on b8 b3)
    (on b10 b9)
    (on b5 b4)
    (on b2 b6)
    (clear b8)
    (clear b10)
    (clear b5)
    (clear b2)
  )
  (:goal
    (and
      (on b2 b3)
    )
  )
)
