(define (problem instance-10)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10)
  (:init
    (handempty)
    (ontable b5)
    (ontable b4)
    (ontable b8)
    (ontable b1)
    (ontable b6)
    (ontable b7)
    (on b2 b7)
    (on b10 b1)
    (on b9 b4)
    (on b3 b9)
    (clear b5)
    (clear b8)
    (clear b6)
    (clear b2)
    (clear b10)
    (clear b3)
  )
  (:goal
    (and
      (on b2 b5)
    )
  )
)
