(define (problem instance-11)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10 b11)
  (:init
    (handempty)
    (ontable b5)
    (ontable b2)
    (ontable b11)
    (ontable b4)
    (ontable b8)
    (ontable b10)
    (on b6 b2)
    (on b1 b8)
    (on b7 b5)
    (on b9 b6)
    (on b3 b1)
    (clear b11)
    (clear b4)
    (clear b10)
    (clear b7)
    (clear b9)
    (clear b3)
  )
  (:goal
    (and
      (on b6 b11)
    )
  )
)
