(define (problem instance-10)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10)
  (:init
    (handempty)
    (ontable b10)
    (ontable b2)
    (ontable b4)
    (ontable b9)
    (ontable b5)
    (ontable b6)
    (on b8 b10)
    (on b1 b6)
    (on b3 b1)
    (on b7 b4)
    (clear b2)
    (clear b9)
    (clear b5)
    (clear b8)
    (clear b3)
    (clear b7)
  )
  (:goal
    (and
      (on b10 b9)
    )
  )
)
