(define (problem instance-8)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8)
  (:init
    (handempty)
    (ontable b5)
    (ontable b7)
    (ontable b8)
    (ontable b2)
    (ontable b1)
    (ontable b3)
    (ontable b4)
    (on b6 b7)
    (clear b5)
    (clear b8)
    (clear b2)
    (clear b1)
    (clear b3)
    (clear b4)
    (clear b6)
  )
  (:goal
    (and
      (on b1 b5)
    )
  )
)
