(define (problem instance-10)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10)
  (:init
    (handempty)
    (ontable b6)
    (ontable b3)
    (ontable b8)
    (ontable b4)
    (ontable b5)
    (on b10 b4)
    (on b9 b6)
    (on b2 b5)
    (on b1 b10)
    (on b7 b8)
    (clear b3)
    (clear b9)
    (clear b2)
    (clear b1)
    (clear b7)
  )
  (:goal
    (and
      (on b8 b5)
    )
  )
)
