(define (problem instance-8)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8)
  (:init
    (handempty)
    (ontable b2)
    (ontable b4)
    (ontable b7)
    (ontable b6)
    (ontable b5)
    (ontable b8)
    (on b3 b2)
    (on b1 b4)
    (clear b7)
    (clear b6)
    (clear b5)
    (clear b8)
    (clear b3)
    (clear b1)
  )
  (:goal
    (and
      (on b3 b6)
    )
  )
)
