(define (problem instance-11)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10 b11)
  (:init
    (handempty)
    (ontable b9)
    (ontable b10)
    (ontable b7)
    (ontable b6)
    (ontable b11)
    (ontable b5)
    (ontable b8)
    (ontable b1)
    (on b4 b9)
    (on b2 b1)
    (on b3 b6)
    (clear b10)
    (clear b7)
    (clear b11)
    (clear b5)
    (clear b8)
    (clear b4)
    (clear b2)
    (clear b3)
  )
  (:goal
    (and
      (on b2 b4)
    )
  )
)
