(define (problem instance-10)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10)
  (:init
    (handempty)
    (ontable b3)
    (ontable b7)
    (ontable b4)
    (ontable b5)
    (ontable b2)
    (ontable b1)
    (ontable b9)
    (on b6 b5)
    (on b8 b7)
    (on b10 b9)
    (clear b3)
    (clear b4)
    (clear b2)
    (clear b1)
    (clear b6)
    (clear b8)
    (clear b10)
  )
  (:goal
    (and
      (on b5 b1)
    )
  )
)
