(define (problem instance-11)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10 b11)
  (:init
    (handempty)
    (ontable b7)
    (ontable b11)
    (ontable b3)
    (ontable b4)
    (ontable b6)
    (ontable b5)
    (on b9 b3)
    (on b10 b4)
    (on b2 b10)
    (on b8 b11)
    (on b1 b5)
    (clear b7)
    (clear b6)
    (clear b9)
    (clear b2)
    (clear b8)
    (clear b1)
  )
  (:goal
    (and
      (on b9 b7)
    )
  )
)
