(define (problem instance-12)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10 b11 b12)
  (:init
    (handempty)
    (ontable b2)
    (ontable b11)
    (ontable b9)
    (ontable b4)
    (ontable b7)
    (ontable b12)
    (ontable b5)
    (ontable b6)
    (ontable b3)
    (on b8 b5)
    (on b1 b9)
    (on b10 b1)
    (clear b2)
    (clear b11)
    (clear b4)
    (clear b7)
    (clear b12)
    (clear b6)
    (clear b3)
    (clear b8)
    (clear b10)
  )
  (:goal
    (and
      (on b8 b10)
    )
  )
)
