(define (problem instance-9)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9)
  (:init
    (handempty)
    (ontable b7)
    (ontable b6)
    (ontable b5)
    (ontable b2)
    (ontable b1)
    (ontable b9)
    (on b3 b7)
    (on b8 b2)
    (on b4 b5)
    (clear b6)
    (clear b1)
    (clear b9)
    (clear b3)
    (clear b8)
    (clear b4)
  )
  (:goal
    (and
      (on b9 b8)
    )
  )
)
