(define (problem instance-10)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10)
  (:init
    (handempty)
    (ontable b2)
    (ontable b7)
    (ontable b5)
    (ontable b4)
    (ontable b8)
    (on b9 b7)
    (on b3 b2)
    (on b10 b9)
    (on b6 b4)
    (on b1 b3)
    (clear b5)
    (clear b8)
    (clear b10)
    (clear b6)
    (clear b1)
  )
  (:goal
    (and
      (on b6 b5)
    )
  )
)
