(define (problem instance-12)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10 b11 b12)
  (:init
    (handempty)
    (ontable b1)
    (ontable b12)
    (ontable b5)
    (ontable b3)
    (ontable b7)
    (ontable b9)
    (ontable b6)
    (ontable b11)
    (ontable b2)
    (ontable b8)
    (on b10 b11)
    (on b4 b7)
    (clear b1)
    (clear b12)
    (clear b5)
    (clear b3)
    (clear b9)
    (clear b6)
    (clear b2)
    (clear b8)
    (clear b10)
    (clear b4)
  )
  (:goal
    (and
      (on b11 b10)
    )
  )
)
