(define (problem instance-11)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10 b11)
  (:init
    (handempty)
    (ontable b6)
    (ontable b11)
    (ontable b5)
    (ontable b3)
    (ontable b1)
    (ontable b4)
    (ontable b7)
    (ontable b10)
    (on b8 b5)
    (on b9 b1)
    (on b2 b10)
    (clear b6)
    (clear b11)
    (clear b3)
    (clear b4)
    (clear b7)
    (clear b8)
    (clear b9)
    (clear b2)
  )
  (:goal
    (and
      (on b7 b10)
    )
  )
)
