(define (problem instance-10)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10)
  (:init
    (handempty)
    (ontable b5)
    (ontable b1)
    (ontable b10)
    (on b6 b5)
    (on b3 b10)
    (on b2 b3)
    (on b7 b1)
    (on b9 b2)
    (on b4 b7)
    (on b8 b6)
    (clear b9)
    (clear b4)
    (clear b8)
  )
  (:goal
    (and
      (on b2 b1)
    )
  )
)
