(define (problem instance-11)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10 b11)
  (:init
    (handempty)
    (ontable b3)
    (ontable b2)
    (ontable b8)
    (ontable b10)
    (ontable b5)
    (ontable b4)
    (on b6 b10)
    (on b1 b3)
    (on b9 b4)
    (on b7 b9)
    (on b11 b5)
    (clear b2)
    (clear b8)
    (clear b6)
    (clear b1)
    (clear b7)
    (clear b11)
  )
  (:goal
    (and
      (on b11 b9)
    )
  )
)
