(define (problem instance-9)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9)
  (:init
    (handempty)
    (ontable b3)
    (ontable b1)
    (ontable b8)
    (ontable b5)
    (ontable b9)
    (ontable b6)
    (ontable b2)
    (on b7 b8)
    (on b4 b2)
    (clear b3)
    (clear b1)
    (clear b5)
    (clear b9)
    (clear b6)
    (clear b7)
    (clear b4)
  )
  (:goal
    (and
      (on b5 b4)
    )
  )
)
