(define (problem instance-10)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10)
  (:init
    (handempty)
    (ontable b9)
    (ontable b4)
    (ontable b2)
    (ontable b3)
    (ontable b7)
    (ontable b6)
    (on b1 b3)
    (on b10 b1)
    (on b5 b10)
    (on b8 b9)
    (clear b4)
    (clear b2)
    (clear b7)
    (clear b6)
    (clear b5)
    (clear b8)
  )
  (:goal
    (and
      (on b8 b4)
    )
  )
)
