(define (problem instance-10)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10)
  (:init
    (handempty)
    (ontable b2)
    (ontable b5)
    (ontable b9)
    (ontable b10)
    (ontable b8)
    (ontable b6)
    (ontable b4)
    (ontable b7)
    (on b1 b7)
    (on b3 b4)
    (clear b2)
    (clear b5)
    (clear b9)
    (clear b10)
    (clear b8)
    (clear b6)
    (clear b1)
    (clear b3)
  )
  (:goal
    (and
      (on b10 b8)
    )
  )
)
