(define (problem instance-11)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10 b11)
  (:init
    (handempty)
    (ontable b2)
    (ontable b3)
    (ontable b9)
    (ontable b4)
    (ontable b11)
    (ontable b8)
    (ontable b6)
    (ontable b7)
    (ontable b1)
    (on b5 b8)
    (on b10 b4)
    (clear b2)
    (clear b3)
    (clear b9)
    (clear b11)
    (clear b6)
    (clear b7)
    (clear b1)
    (clear b5)
    (clear b10)
  )
  (:goal
    (and
      (on b3 b9)
    )
  )
)
