(define (problem instance-11)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10 b11)
  (:init
    (handempty)
    (ontable b1)
    (ontable b5)
    (ontable b10)
    (ontable b8)
    (ontable b4)
    (ontable b11)
    (ontable b6)
    (on b2 b11)
    (on b7 b8)
    (on b3 b6)
    (on b9 b10)
    (clear b1)
    (clear b5)
    (clear b4)
    (clear b2)
    (clear b7)
    (clear b3)
    (clear b9)
  )
  (:goal
    (and
      (on b11 b5)
    )
  )
)
