(define (problem instance-9)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9)
  (:init
    (handempty)
    (ontable b5)
    (ontable b4)
    (ontable b6)
    (on b2 b5)
    (on b7 b4)
    (on b9 b7)
    (on b8 b6)
    (on b1 b8)
    (on b3 b1)
    (clear b2)
    (clear b9)
    (clear b3)
  )
  (:goal
    (and
      (on b2 b1)
    )
  )
)
