(define (problem instance-10)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10)
  (:init
    (handempty)
    (ontable b8)
    (ontable b5)
    (ontable b2)
    (ontable b9)
    (ontable b7)
    (ontable b3)
    (on b1 b7)
    (on b10 b9)
    (on b4 b5)
    (on b6 b4)
    (clear b8)
    (clear b2)
    (clear b3)
    (clear b1)
    (clear b10)
    (clear b6)
  )
  (:goal
    (and
      (on b3 b10)
    )
  )
)
