(define (problem instance-10)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10)
  (:init
    (handempty)
    (ontable b3)
    (ontable b5)
    (ontable b10)
    (ontable b6)
    (ontable b2)
    (on b8 b6)
    (on b1 b5)
    (on b9 b2)
    (on b4 b3)
    (on b7 b8)
    (clear b10)
    (clear b1)
    (clear b9)
    (clear b4)
    (clear b7)
  )
  (:goal
    (and
      (on b8 b9)
    )
  )
)
