(define (problem instance-10)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10)
  (:init
    (handempty)
    (ontable b2)
    (ontable b10)
    (ontable b9)
    (ontable b6)
    (ontable b4)
    (on b7 b9)
    (on b8 b2)
    (on b3 b10)
    (on b5 b8)
    (on b1 b5)
    (clear b6)
    (clear b4)
    (clear b7)
    (clear b3)
    (clear b1)
  )
  (:goal
    (and
      (on b4 b8)
    )
  )
)
