(define (problem instance-12)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10 b11 b12)
  (:init
    (handempty)
    (ontable b4)
    (ontable b3)
    (ontable b2)
    (ontable b12)
    (ontable b9)
    (ontable b10)
    (ontable b7)
    (ontable b6)
    (ontable b1)
    (on b11 b9)
    (on b5 b10)
    (on b8 b5)
    (clear b4)
    (clear b3)
    (clear b2)
    (clear b12)
    (clear b7)
    (clear b6)
    (clear b1)
    (clear b11)
    (clear b8)
  )
  (:goal
    (and
      (on b12 b7)
    )
  )
)
