(define (problem instance-8)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8)
  (:init
    (handempty)
    (ontable b6)
    (ontable b4)
    (ontable b5)
    (ontable b2)
    (ontable b7)
    (on b1 b4)
    (on b8 b1)
    (on b3 b2)
    (clear b6)
    (clear b5)
    (clear b7)
    (clear b8)
    (clear b3)
  )
  (:goal
    (and
      (on b8 b2)
    )
  )
)
