(define (problem instance-9)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9)
  (:init
    (handempty)
    (ontable b6)
    (ontable b7)
    (ontable b3)
    (ontable b1)
    (ontable b5)
    (ontable b9)
    (on b4 b5)
    (on b8 b9)
    (on b2 b8)
    (clear b6)
    (clear b7)
    (clear b3)
    (clear b1)
    (clear b4)
    (clear b2)
  )
  (:goal
    (and
      (on b8 b2)
    )
  )
)
