(define (problem instance-11)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10 b11)
  (:init
    (handempty)
    (ontable b1)
    (ontable b11)
    (ontable b8)
    (ontable b7)
    (ontable b9)
    (ontable b6)
    (ontable b10)
    (ontable b3)
    (ontable b4)
    (ontable b5)
    (on b2 b4)
    (clear b1)
    (clear b11)
    (clear b8)
    (clear b7)
    (clear b9)
    (clear b6)
    (clear b10)
    (clear b3)
    (clear b5)
    (clear b2)
  )
  (:goal
    (and
      (on b9 b11)
    )
  )
)
