(define (problem instance-10)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10)
  (:init
    (handempty)
    (ontable b8)
    (ontable b1)
    (ontable b6)
    (ontable b10)
    (ontable b3)
    (ontable b5)
    (ontable b2)
    (ontable b9)
    (ontable b7)
    (on b4 b8)
    (clear b1)
    (clear b6)
    (clear b10)
    (clear b3)
    (clear b5)
    (clear b2)
    (clear b9)
    (clear b7)
    (clear b4)
  )
  (:goal
    (and
      (on b2 b6)
    )
  )
)
