(define (problem instance-8)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8)
  (:init
    (handempty)
    (ontable b6)
    (ontable b5)
    (ontable b8)
    (ontable b3)
    (ontable b7)
    (on b4 b7)
    (on b2 b5)
    (on b1 b4)
    (clear b6)
    (clear b8)
    (clear b3)
    (clear b2)
    (clear b1)
  )
  (:goal
    (and
      (on b7 b5)
    )
  )
)
