(define (problem instance-11)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10 b11)
  (:init
    (handempty)
    (ontable b4)
    (ontable b8)
    (ontable b1)
    (ontable b10)
    (ontable b2)
    (ontable b5)
    (ontable b9)
    (ontable b11)
    (ontable b6)
    (on b7 b1)
    (on b3 b6)
    (clear b4)
    (clear b8)
    (clear b10)
    (clear b2)
    (clear b5)
    (clear b9)
    (clear b11)
    (clear b7)
    (clear b3)
  )
  (:goal
    (and
      (on b1 b8)
    )
  )
)
