(define (problem instance-9)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9)
  (:init
    (handempty)
    (ontable b5)
    (ontable b7)
    (ontable b6)
    (on b4 b5)
    (on b3 b4)
    (on b9 b3)
    (on b8 b9)
    (on b2 b6)
    (on b1 b7)
    (clear b8)
    (clear b2)
    (clear b1)
  )
  (:goal
    (and
      (on b5 b2)
    )
  )
)
