(define (problem instance-11)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10 b11)
  (:init
    (handempty)
    (ontable b1)
    (ontable b11)
    (ontable b8)
    (ontable b10)
    (ontable b2)
    (ontable b4)
    (on b3 b8)
    (on b7 b3)
    (on b9 b2)
    (on b5 b9)
    (on b6 b5)
    (clear b1)
    (clear b11)
    (clear b10)
    (clear b4)
    (clear b7)
    (clear b6)
  )
  (:goal
    (and
      (on b2 b5)
    )
  )
)
