(define (problem instance-9)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9)
  (:init
    (handempty)
    (ontable b2)
    (ontable b1)
    (ontable b8)
    (ontable b9)
    (ontable b4)
    (ontable b6)
    (on b3 b6)
    (on b5 b1)
    (on b7 b8)
    (clear b2)
    (clear b9)
    (clear b4)
    (clear b3)
    (clear b5)
    (clear b7)
  )
  (:goal
    (and
      (on b2 b5)
    )
  )
)
