(define (problem instance-12)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10 b11 b12)
  (:init
    (handempty)
    (ontable b8)
    (ontable b4)
    (ontable b1)
    (ontable b3)
    (ontable b9)
    (ontable b12)
    (ontable b10)
    (ontable b11)
    (ontable b6)
    (ontable b5)
    (on b7 b8)
    (on b2 b9)
    (clear b4)
    (clear b1)
    (clear b3)
    (clear b12)
    (clear b10)
    (clear b11)
    (clear b6)
    (clear b5)
    (clear b7)
    (clear b2)
  )
  (:goal
    (and
      (on b6 b1)
    )
  )
)
