(define (problem instance-12)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10 b11 b12)
  (:init
    (handempty)
    (ontable b4)
    (ontable b3)
    (ontable b11)
    (ontable b9)
    (ontable b6)
    (ontable b8)
    (ontable b2)
    (ontable b10)
    (ontable b5)
    (on b7 b11)
    (on b1 b3)
    (on b12 b2)
    (clear b4)
    (clear b9)
    (clear b6)
    (clear b8)
    (clear b10)
    (clear b5)
    (clear b7)
    (clear b1)
    (clear b12)
  )
  (:goal
    (and
      (on b5 b7)
    )
  )
)
