(define (problem instance-9)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9)
  (:init
    (handempty)
    (ontable b9)
    (ontable b8)
    (ontable b2)
    (ontable b1)
    (ontable b5)
    (on b7 b8)
    (on b4 b9)
    (on b3 b2)
    (on b6 b3)
    (clear b1)
    (clear b5)
    (clear b7)
    (clear b4)
    (clear b6)
  )
  (:goal
    (and
      (on b5 b4)
    )
  )
)
