(define (problem instance-10)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10)
  (:init
    (handempty)
    (ontable b5)
    (ontable b9)
    (ontable b6)
    (ontable b7)
    (ontable b2)
    (ontable b4)
    (ontable b1)
    (on b10 b9)
    (on b8 b1)
    (on b3 b8)
    (clear b5)
    (clear b6)
    (clear b7)
    (clear b2)
    (clear b4)
    (clear b10)
    (clear b3)
  )
  (:goal
    (and
      (on b1 b3)
    )
  )
)
