(define (problem instance-10)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10)
  (:init
    (handempty)
    (ontable b3)
    (ontable b7)
    (ontable b1)
    (ontable b8)
    (ontable b2)
    (ontable b5)
    (ontable b10)
    (on b9 b2)
    (on b4 b8)
    (on b6 b10)
    (clear b3)
    (clear b7)
    (clear b1)
    (clear b5)
    (clear b9)
    (clear b4)
    (clear b6)
  )
  (:goal
    (and
      (on b3 b5)
    )
  )
)
