(define (problem instance-11)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10 b11)
  (:init
    (handempty)
    (ontable b10)
    (ontable b7)
    (ontable b3)
    (ontable b1)
    (ontable b9)
    (ontable b5)
    (on b11 b1)
    (on b8 b3)
    (on b4 b7)
    (on b6 b4)
    (on b2 b8)
    (clear b10)
    (clear b9)
    (clear b5)
    (clear b11)
    (clear b6)
    (clear b2)
  )
  (:goal
    (and
      (on b1 b10)
    )
  )
)
