(define (problem instance-10)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10)
  (:init
    (handempty)
    (ontable b8)
    (ontable b10)
    (ontable b4)
    (ontable b2)
    (ontable b3)
    (ontable b6)
    (ontable b9)
    (on b7 b2)
    (on b1 b4)
    (on b5 b1)
    (clear b8)
    (clear b10)
    (clear b3)
    (clear b6)
    (clear b9)
    (clear b7)
    (clear b5)
  )
  (:goal
    (and
      (on b6 b7)
    )
  )
)
