(define (problem instance-10)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10)
  (:init
    (handempty)
    (ontable b3)
    (ontable b5)
    (ontable b10)
    (on b8 b5)
    (on b9 b10)
    (on b7 b8)
    (on b1 b3)
    (on b4 b7)
    (on b2 b1)
    (on b6 b9)
    (clear b4)
    (clear b2)
    (clear b6)
  )
  (:goal
    (and
      (on b5 b2)
    )
  )
)
