(define (problem instance-8)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8)
  (:init
    (handempty)
    (ontable b7)
    (ontable b5)
    (ontable b6)
    (ontable b8)
    (ontable b4)
    (ontable b3)
    (on b2 b8)
    (on b1 b5)
    (clear b7)
    (clear b6)
    (clear b4)
    (clear b3)
    (clear b2)
    (clear b1)
  )
  (:goal
    (and
      (on b5 b2)
    )
  )
)
