(define (problem instance-10)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10)
  (:init
    (handempty)
    (ontable b1)
    (ontable b2)
    (ontable b3)
    (ontable b7)
    (ontable b5)
    (ontable b6)
    (ontable b9)
    (ontable b4)
    (on b8 b9)
    (on b10 b3)
    (clear b1)
    (clear b2)
    (clear b7)
    (clear b5)
    (clear b6)
    (clear b4)
    (clear b8)
    (clear b10)
  )
  (:goal
    (and
      (on b7 b3)
    )
  )
)
