(define (problem instance-9)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9)
  (:init
    (handempty)
    (ontable b2)
    (ontable b7)
    (ontable b3)
    (ontable b6)
    (ontable b4)
    (ontable b8)
    (on b5 b3)
    (on b1 b2)
    (on b9 b4)
    (clear b7)
    (clear b6)
    (clear b8)
    (clear b5)
    (clear b1)
    (clear b9)
  )
  (:goal
    (and
      (on b3 b6)
    )
  )
)
