(define (problem instance-11)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10 b11)
  (:init
    (handempty)
    (ontable b9)
    (ontable b3)
    (ontable b4)
    (ontable b8)
    (ontable b11)
    (ontable b2)
    (ontable b5)
    (ontable b6)
    (ontable b7)
    (on b1 b4)
    (on b10 b9)
    (clear b3)
    (clear b8)
    (clear b11)
    (clear b2)
    (clear b5)
    (clear b6)
    (clear b7)
    (clear b1)
    (clear b10)
  )
  (:goal
    (and
      (on b4 b8)
    )
  )
)
