(define (problem instance-9)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9)
  (:init
    (handempty)
    (ontable b8)
    (ontable b7)
    (ontable b1)
    (ontable b5)
    (on b3 b8)
    (on b4 b1)
    (on b9 b3)
    (on b6 b4)
    (on b2 b7)
    (clear b5)
    (clear b9)
    (clear b6)
    (clear b2)
  )
  (:goal
    (and
      (on b2 b4)
    )
  )
)
