(define (problem instance-12)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10 b11 b12)
  (:init
    (handempty)
    (ontable b10)
    (ontable b6)
    (ontable b12)
    (ontable b7)
    (ontable b3)
    (ontable b8)
    (ontable b9)
    (ontable b4)
    (on b1 b9)
    (on b11 b8)
    (on b5 b6)
    (on b2 b4)
    (clear b10)
    (clear b12)
    (clear b7)
    (clear b3)
    (clear b1)
    (clear b11)
    (clear b5)
    (clear b2)
  )
  (:goal
    (and
      (on b12 b1)
    )
  )
)
