(define (problem instance-11)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10 b11)
  (:init
    (handempty)
    (ontable b6)
    (ontable b8)
    (ontable b7)
    (ontable b5)
    (ontable b11)
    (ontable b3)
    (on b10 b6)
    (on b9 b5)
    (on b2 b11)
    (on b4 b10)
    (on b1 b4)
    (clear b8)
    (clear b7)
    (clear b3)
    (clear b9)
    (clear b2)
    (clear b1)
  )
  (:goal
    (and
      (on b7 b11)
    )
  )
)
