(define (problem instance-8)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8)
  (:init
    (handempty)
    (ontable b3)
    (ontable b4)
    (ontable b1)
    (ontable b2)
    (ontable b8)
    (ontable b5)
    (on b6 b3)
    (on b7 b6)
    (clear b4)
    (clear b1)
    (clear b2)
    (clear b8)
    (clear b5)
    (clear b7)
  )
  (:goal
    (and
      (on b7 b2)
    )
  )
)
