(define (problem instance-9)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9)
  (:init
    (handempty)
    (ontable b5)
    (ontable b1)
    (ontable b6)
    (ontable b4)
    (ontable b9)
    (ontable b7)
    (ontable b8)
    (on b2 b7)
    (on b3 b5)
    (clear b1)
    (clear b6)
    (clear b4)
    (clear b9)
    (clear b8)
    (clear b2)
    (clear b3)
  )
  (:goal
    (and
      (on b7 b1)
    )
  )
)
