(define (problem instance-12)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10 b11 b12)
  (:init
    (handempty)
    (ontable b8)
    (ontable b9)
    (ontable b11)
    (ontable b4)
    (ontable b10)
    (ontable b3)
    (ontable b1)
    (ontable b6)
    (ontable b7)
    (ontable b12)
    (on b2 b4)
    (on b5 b10)
    (clear b8)
    (clear b9)
    (clear b11)
    (clear b3)
    (clear b1)
    (clear b6)
    (clear b7)
    (clear b12)
    (clear b2)
    (clear b5)
  )
  (:goal
    (and
      (on b3 b6)
    )
  )
)
