(define (problem instance-9)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9)
  (:init
    (handempty)
    (ontable b1)
    (ontable b8)
    (ontable b3)
    (ontable b9)
    (ontable b7)
    (on b5 b3)
    (on b4 b7)
    (on b2 b4)
    (on b6 b1)
    (clear b8)
    (clear b9)
    (clear b5)
    (clear b2)
    (clear b6)
  )
  (:goal
    (and
      (on b8 b1)
    )
  )
)
