(define (problem instance-10)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10)
  (:init
    (handempty)
    (ontable b3)
    (ontable b5)
    (ontable b9)
    (ontable b2)
    (ontable b10)
    (on b8 b5)
    (on b6 b8)
    (on b7 b3)
    (on b4 b9)
    (on b1 b7)
    (clear b2)
    (clear b10)
    (clear b6)
    (clear b4)
    (clear b1)
  )
  (:goal
    (and
      (on b10 b4)
    )
  )
)
