(define (problem instance-9)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9)
  (:init
    (handempty)
    (ontable b3)
    (ontable b8)
    (ontable b7)
    (ontable b6)
    (ontable b9)
    (ontable b2)
    (ontable b5)
    (on b4 b5)
    (on b1 b7)
    (clear b3)
    (clear b8)
    (clear b6)
    (clear b9)
    (clear b2)
    (clear b4)
    (clear b1)
  )
  (:goal
    (and
      (on b1 b4)
    )
  )
)
