(define (problem instance-13)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10 b11 b12 b13)
  (:init
    (handempty)
    (ontable b1)
    (ontable b12)
    (ontable b5)
    (ontable b7)
    (ontable b4)
    (ontable b2)
    (ontable b9)
    (ontable b13)
    (ontable b6)
    (ontable b10)
    (on b11 b10)
    (on b3 b12)
    (on b8 b4)
    (clear b1)
    (clear b5)
    (clear b7)
    (clear b2)
    (clear b9)
    (clear b13)
    (clear b6)
    (clear b11)
    (clear b3)
    (clear b8)
  )
  (:goal
    (and
      (on b8 b3)
    )
  )
)
