(define (problem instance-10)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10)
  (:init
    (handempty)
    (ontable b1)
    (ontable b10)
    (ontable b9)
    (ontable b2)
    (on b5 b1)
    (on b7 b10)
    (on b3 b2)
    (on b8 b7)
    (on b4 b3)
    (on b6 b8)
    (clear b9)
    (clear b5)
    (clear b4)
    (clear b6)
  )
  (:goal
    (and
      (on b2 b8)
    )
  )
)
