(define (problem instance-10)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10)
  (:init
    (handempty)
    (ontable b9)
    (ontable b2)
    (ontable b4)
    (ontable b1)
    (ontable b3)
    (ontable b8)
    (on b10 b8)
    (on b5 b10)
    (on b7 b4)
    (on b6 b2)
    (clear b9)
    (clear b1)
    (clear b3)
    (clear b5)
    (clear b7)
    (clear b6)
  )
  (:goal
    (and
      (on b4 b9)
    )
  )
)
