(define (problem instance-11)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10 b11)
  (:init
    (handempty)
    (ontable b4)
    (ontable b7)
    (ontable b8)
    (ontable b5)
    (ontable b10)
    (ontable b3)
    (on b6 b8)
    (on b2 b3)
    (on b11 b5)
    (on b9 b6)
    (on b1 b2)
    (clear b4)
    (clear b7)
    (clear b10)
    (clear b11)
    (clear b9)
    (clear b1)
  )
  (:goal
    (and
      (on b5 b8)
    )
  )
)
