(define (problem instance-9)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9)
  (:init
    (handempty)
    (ontable b2)
    (ontable b8)
    (ontable b4)
    (ontable b3)
    (ontable b9)
    (on b1 b2)
    (on b5 b8)
    (on b6 b5)
    (on b7 b1)
    (clear b4)
    (clear b3)
    (clear b9)
    (clear b6)
    (clear b7)
  )
  (:goal
    (and
      (on b8 b1)
    )
  )
)
