(define (problem instance-10)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10)
  (:init
    (handempty)
    (ontable b1)
    (ontable b10)
    (ontable b6)
    (ontable b2)
    (on b4 b2)
    (on b9 b1)
    (on b8 b10)
    (on b5 b9)
    (on b3 b8)
    (on b7 b4)
    (clear b6)
    (clear b5)
    (clear b3)
    (clear b7)
  )
  (:goal
    (and
      (on b2 b8)
    )
  )
)
