(define (problem instance-9)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9)
  (:init
    (handempty)
    (ontable b5)
    (ontable b4)
    (ontable b9)
    (on b3 b9)
    (on b6 b5)
    (on b2 b4)
    (on b8 b3)
    (on b7 b8)
    (on b1 b6)
    (clear b2)
    (clear b7)
    (clear b1)
  )
  (:goal
    (and
      (on b9 b2)
    )
  )
)
