(define (problem instance-11)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10 b11)
  (:init
    (handempty)
    (ontable b1)
    (ontable b6)
    (ontable b10)
    (ontable b11)
    (ontable b9)
    (ontable b2)
    (ontable b7)
    (ontable b3)
    (on b4 b3)
    (on b5 b4)
    (on b8 b9)
    (clear b1)
    (clear b6)
    (clear b10)
    (clear b11)
    (clear b2)
    (clear b7)
    (clear b5)
    (clear b8)
  )
  (:goal
    (and
      (on b11 b2)
    )
  )
)
