(define (problem instance-10)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10)
  (:init
    (handempty)
    (ontable b2)
    (ontable b8)
    (ontable b9)
    (ontable b7)
    (ontable b10)
    (ontable b5)
    (ontable b3)
    (ontable b4)
    (on b6 b3)
    (on b1 b5)
    (clear b2)
    (clear b8)
    (clear b9)
    (clear b7)
    (clear b10)
    (clear b4)
    (clear b6)
    (clear b1)
  )
  (:goal
    (and
      (on b3 b9)
    )
  )
)
