(define (problem instance-10)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10)
  (:init
    (handempty)
    (ontable b6)
    (ontable b8)
    (ontable b5)
    (ontable b9)
    (ontable b3)
    (ontable b10)
    (ontable b2)
    (on b1 b9)
    (on b7 b2)
    (on b4 b6)
    (clear b8)
    (clear b5)
    (clear b3)
    (clear b10)
    (clear b1)
    (clear b7)
    (clear b4)
  )
  (:goal
    (and
      (on b5 b9)
    )
  )
)
