(define (problem instance-12)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10 b11 b12)
  (:init
    (handempty)
    (ontable b11)
    (ontable b8)
    (ontable b3)
    (ontable b10)
    (ontable b2)
    (ontable b4)
    (ontable b6)
    (ontable b5)
    (ontable b1)
    (on b9 b1)
    (on b7 b8)
    (on b12 b5)
    (clear b11)
    (clear b3)
    (clear b10)
    (clear b2)
    (clear b4)
    (clear b6)
    (clear b9)
    (clear b7)
    (clear b12)
  )
  (:goal
    (and
      (on b1 b10)
    )
  )
)
