(define (problem instance-12)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10 b11 b12)
  (:init
    (handempty)
    (ontable b9)
    (ontable b1)
    (ontable b3)
    (ontable b10)
    (ontable b4)
    (ontable b11)
    (ontable b7)
    (ontable b2)
    (ontable b6)
    (on b12 b10)
    (on b5 b3)
    (on b8 b2)
    (clear b9)
    (clear b1)
    (clear b4)
    (clear b11)
    (clear b7)
    (clear b6)
    (clear b12)
    (clear b5)
    (clear b8)
  )
  (:goal
    (and
      (on b10 b7)
    )
  )
)
