(define (problem instance-9)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9)
  (:init
    (handempty)
    (ontable b2)
    (ontable b5)
    (ontable b7)
    (ontable b9)
    (on b4 b2)
    (on b8 b9)
    (on b6 b5)
    (on b1 b8)
    (on b3 b4)
    (clear b7)
    (clear b6)
    (clear b1)
    (clear b3)
  )
  (:goal
    (and
      (on b7 b3)
    )
  )
)
