(define (problem instance-11)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10 b11)
  (:init
    (handempty)
    (ontable b5)
    (ontable b7)
    (ontable b6)
    (ontable b10)
    (ontable b8)
    (ontable b3)
    (ontable b4)
    (ontable b1)
    (on b9 b8)
    (on b2 b6)
    (on b11 b2)
    (clear b5)
    (clear b7)
    (clear b10)
    (clear b3)
    (clear b4)
    (clear b1)
    (clear b9)
    (clear b11)
  )
  (:goal
    (and
      (on b1 b4)
    )
  )
)
