(define (problem instance-10)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10)
  (:init
    (handempty)
    (ontable b6)
    (ontable b10)
    (ontable b9)
    (ontable b1)
    (ontable b4)
    (ontable b5)
    (ontable b2)
    (ontable b7)
    (ontable b3)
    (on b8 b2)
    (clear b6)
    (clear b10)
    (clear b9)
    (clear b1)
    (clear b4)
    (clear b5)
    (clear b7)
    (clear b3)
    (clear b8)
  )
  (:goal
    (and
      (on b8 b3)
    )
  )
)
