(define (problem instance-10)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10)
  (:init
    (handempty)
    (ontable b3)
    (ontable b4)
    (ontable b9)
    (ontable b2)
    (ontable b10)
    (ontable b8)
    (ontable b5)
    (ontable b6)
    (ontable b7)
    (ontable b1)
    (clear b3)
    (clear b4)
    (clear b9)
    (clear b2)
    (clear b10)
    (clear b8)
    (clear b5)
    (clear b6)
    (clear b7)
    (clear b1)
  )
  (:goal
    (and
      (on b9 b7)
    )
  )
)
