(define (problem instance-12)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10 b11 b12)
  (:init
    (handempty)
    (ontable b11)
    (ontable b4)
    (ontable b9)
    (ontable b5)
    (ontable b7)
    (ontable b1)
    (ontable b2)
    (ontable b10)
    (ontable b12)
    (ontable b6)
    (on b3 b7)
    (on b8 b3)
    (clear b11)
    (clear b4)
    (clear b9)
    (clear b5)
    (clear b1)
    (clear b2)
    (clear b10)
    (clear b12)
    (clear b6)
    (clear b8)
  )
  (:goal
    (and
      (on b2 b7)
    )
  )
)
