(define (problem instance-10)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10)
  (:init
    (handempty)
    (ontable b5)
    (ontable b4)
    (ontable b3)
    (on b10 b4)
    (on b7 b10)
    (on b6 b3)
    (on b2 b7)
    (on b9 b5)
    (on b8 b2)
    (on b1 b6)
    (clear b9)
    (clear b8)
    (clear b1)
  )
  (:goal
    (and
      (on b6 b9)
    )
  )
)
