(define (problem instance-9)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9)
  (:init
    (handempty)
    (ontable b9)
    (ontable b7)
    (ontable b5)
    (ontable b6)
    (ontable b2)
    (on b3 b6)
    (on b8 b9)
    (on b4 b8)
    (on b1 b4)
    (clear b7)
    (clear b5)
    (clear b2)
    (clear b3)
    (clear b1)
  )
  (:goal
    (and
      (on b3 b8)
    )
  )
)
