(define (problem instance-11)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10 b11)
  (:init
    (handempty)
    (ontable b4)
    (ontable b10)
    (ontable b9)
    (ontable b6)
    (ontable b2)
    (ontable b1)
    (on b7 b9)
    (on b8 b7)
    (on b11 b2)
    (on b3 b11)
    (on b5 b8)
    (clear b4)
    (clear b10)
    (clear b6)
    (clear b1)
    (clear b3)
    (clear b5)
  )
  (:goal
    (and
      (on b6 b1)
    )
  )
)
