(define (problem instance-11)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10 b11)
  (:init
    (handempty)
    (ontable b11)
    (ontable b3)
    (ontable b10)
    (ontable b1)
    (ontable b9)
    (ontable b8)
    (ontable b7)
    (on b6 b10)
    (on b2 b7)
    (on b4 b2)
    (on b5 b8)
    (clear b11)
    (clear b3)
    (clear b1)
    (clear b9)
    (clear b6)
    (clear b4)
    (clear b5)
  )
  (:goal
    (and
      (on b9 b10)
    )
  )
)
