(define (problem instance-11)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10 b11)
  (:init
    (handempty)
    (ontable b11)
    (ontable b8)
    (ontable b4)
    (ontable b7)
    (ontable b2)
    (ontable b9)
    (ontable b1)
    (ontable b6)
    (ontable b3)
    (on b10 b8)
    (on b5 b2)
    (clear b11)
    (clear b4)
    (clear b7)
    (clear b9)
    (clear b1)
    (clear b6)
    (clear b3)
    (clear b10)
    (clear b5)
  )
  (:goal
    (and
      (on b3 b6)
    )
  )
)
