(define (problem instance-9)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9)
  (:init
    (handempty)
    (ontable b2)
    (ontable b1)
    (ontable b8)
    (ontable b6)
    (ontable b3)
    (ontable b5)
    (on b9 b3)
    (on b4 b1)
    (on b7 b9)
    (clear b2)
    (clear b8)
    (clear b6)
    (clear b5)
    (clear b4)
    (clear b7)
  )
  (:goal
    (and
      (on b9 b5)
    )
  )
)
