(define (problem instance-9)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9)
  (:init
    (handempty)
    (ontable b8)
    (ontable b3)
    (ontable b1)
    (ontable b6)
    (on b9 b6)
    (on b2 b3)
    (on b7 b1)
    (on b4 b8)
    (on b5 b7)
    (clear b9)
    (clear b2)
    (clear b4)
    (clear b5)
  )
  (:goal
    (and
      (on b9 b7)
    )
  )
)
