(define (problem instance-10)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10)
  (:init
    (handempty)
    (ontable b6)
    (ontable b10)
    (ontable b8)
    (on b4 b6)
    (on b1 b8)
    (on b7 b1)
    (on b2 b4)
    (on b3 b10)
    (on b9 b7)
    (on b5 b2)
    (clear b3)
    (clear b9)
    (clear b5)
  )
  (:goal
    (and
      (on b8 b7)
    )
  )
)
