(define (problem instance-11)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10 b11)
  (:init
    (handempty)
    (ontable b5)
    (ontable b7)
    (ontable b6)
    (ontable b3)
    (ontable b8)
    (ontable b10)
    (on b4 b7)
    (on b11 b6)
    (on b2 b11)
    (on b9 b2)
    (on b1 b9)
    (clear b5)
    (clear b3)
    (clear b8)
    (clear b10)
    (clear b4)
    (clear b1)
  )
  (:goal
    (and
      (on b3 b2)
    )
  )
)
