(define (problem instance-10)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10)
  (:init
    (handempty)
    (ontable b10)
    (ontable b3)
    (ontable b5)
    (ontable b1)
    (ontable b7)
    (ontable b8)
    (on b2 b3)
    (on b6 b7)
    (on b9 b1)
    (on b4 b9)
    (clear b10)
    (clear b5)
    (clear b8)
    (clear b2)
    (clear b6)
    (clear b4)
  )
  (:goal
    (and
      (on b6 b8)
    )
  )
)
