(define (problem instance-8)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8)
  (:init
    (handempty)
    (ontable b2)
    (ontable b6)
    (ontable b1)
    (ontable b8)
    (ontable b7)
    (on b3 b6)
    (on b5 b2)
    (on b4 b7)
    (clear b1)
    (clear b8)
    (clear b3)
    (clear b5)
    (clear b4)
  )
  (:goal
    (and
      (on b6 b8)
    )
  )
)
