(define (problem instance-8)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8)
  (:init
    (handempty)
    (ontable b3)
    (ontable b8)
    (ontable b5)
    (ontable b7)
    (ontable b4)
    (ontable b1)
    (on b6 b5)
    (on b2 b4)
    (clear b3)
    (clear b8)
    (clear b7)
    (clear b1)
    (clear b6)
    (clear b2)
  )
  (:goal
    (and
      (on b1 b6)
    )
  )
)
