(define (problem instance-10)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10)
  (:init
    (handempty)
    (ontable b10)
    (ontable b4)
    (ontable b3)
    (on b8 b4)
    (on b9 b8)
    (on b2 b10)
    (on b6 b9)
    (on b5 b2)
    (on b7 b5)
    (on b1 b3)
    (clear b6)
    (clear b7)
    (clear b1)
  )
  (:goal
    (and
      (on b8 b9)
    )
  )
)
