(define (problem instance-11)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10 b11)
  (:init
    (handempty)
    (ontable b9)
    (ontable b7)
    (ontable b3)
    (ontable b10)
    (ontable b5)
    (ontable b6)
    (ontable b11)
    (ontable b8)
    (on b1 b11)
    (on b4 b9)
    (on b2 b1)
    (clear b7)
    (clear b3)
    (clear b10)
    (clear b5)
    (clear b6)
    (clear b8)
    (clear b4)
    (clear b2)
  )
  (:goal
    (and
      (on b5 b2)
    )
  )
)
