(define (problem instance-11)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10 b11)
  (:init
    (handempty)
    (ontable b8)
    (ontable b4)
    (ontable b11)
    (ontable b9)
    (ontable b7)
    (ontable b2)
    (ontable b10)
    (ontable b3)
    (ontable b1)
    (ontable b6)
    (on b5 b1)
    (clear b8)
    (clear b4)
    (clear b11)
    (clear b9)
    (clear b7)
    (clear b2)
    (clear b10)
    (clear b3)
    (clear b6)
    (clear b5)
  )
  (:goal
    (and
      (on b10 b2)
    )
  )
)
