(define (problem instance-9)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9)
  (:init
    (handempty)
    (ontable b6)
    (ontable b4)
    (ontable b3)
    (ontable b9)
    (ontable b7)
    (ontable b8)
    (on b5 b4)
    (on b1 b9)
    (on b2 b7)
    (clear b6)
    (clear b3)
    (clear b8)
    (clear b5)
    (clear b1)
    (clear b2)
  )
  (:goal
    (and
      (on b9 b1)
    )
  )
)
