(define (problem instance-9)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9)
  (:init
    (handempty)
    (ontable b7)
    (ontable b9)
    (ontable b4)
    (on b6 b7)
    (on b3 b9)
    (on b5 b4)
    (on b2 b6)
    (on b1 b2)
    (on b8 b1)
    (clear b3)
    (clear b5)
    (clear b8)
  )
  (:goal
    (and
      (on b7 b4)
    )
  )
)
