(define (problem instance-8)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8)
  (:init
    (handempty)
    (ontable b5)
    (ontable b3)
    (ontable b6)
    (ontable b7)
    (ontable b8)
    (ontable b2)
    (on b1 b5)
    (on b4 b6)
    (clear b3)
    (clear b7)
    (clear b8)
    (clear b2)
    (clear b1)
    (clear b4)
  )
  (:goal
    (and
      (on b7 b1)
    )
  )
)
