(define (problem instance-9)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9)
  (:init
    (handempty)
    (ontable b8)
    (ontable b4)
    (ontable b1)
    (ontable b6)
    (ontable b9)
    (ontable b7)
    (ontable b2)
    (on b5 b1)
    (on b3 b7)
    (clear b8)
    (clear b4)
    (clear b6)
    (clear b9)
    (clear b2)
    (clear b5)
    (clear b3)
  )
  (:goal
    (and
      (on b6 b8)
    )
  )
)
