(define (problem instance-11)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10 b11)
  (:init
    (handempty)
    (ontable b1)
    (ontable b3)
    (ontable b5)
    (ontable b4)
    (ontable b2)
    (ontable b6)
    (ontable b11)
    (on b10 b3)
    (on b8 b6)
    (on b7 b10)
    (on b9 b8)
    (clear b1)
    (clear b5)
    (clear b4)
    (clear b2)
    (clear b11)
    (clear b7)
    (clear b9)
  )
  (:goal
    (and
      (on b8 b2)
    )
  )
)
