(define (problem instance-9)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9)
  (:init
    (handempty)
    (ontable b3)
    (ontable b8)
    (ontable b9)
    (ontable b4)
    (on b7 b9)
    (on b1 b7)
    (on b5 b4)
    (on b2 b8)
    (on b6 b2)
    (clear b3)
    (clear b1)
    (clear b5)
    (clear b6)
  )
  (:goal
    (and
      (on b5 b9)
    )
  )
)
