(define (problem instance-9)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9)
  (:init
    (handempty)
    (ontable b8)
    (ontable b3)
    (ontable b9)
    (on b7 b3)
    (on b6 b9)
    (on b4 b8)
    (on b5 b7)
    (on b1 b4)
    (on b2 b1)
    (clear b6)
    (clear b5)
    (clear b2)
  )
  (:goal
    (and
      (on b1 b3)
    )
  )
)
