(define (problem instance-9)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9)
  (:init
    (handempty)
    (ontable b2)
    (ontable b4)
    (ontable b9)
    (ontable b7)
    (ontable b3)
    (ontable b8)
    (ontable b1)
    (on b6 b4)
    (on b5 b8)
    (clear b2)
    (clear b9)
    (clear b7)
    (clear b3)
    (clear b1)
    (clear b6)
    (clear b5)
  )
  (:goal
    (and
      (on b8 b4)
    )
  )
)
