(define (problem instance-11)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10 b11)
  (:init
    (handempty)
    (ontable b5)
    (ontable b1)
    (ontable b6)
    (ontable b3)
    (ontable b9)
    (ontable b4)
    (ontable b11)
    (on b10 b3)
    (on b8 b5)
    (on b2 b4)
    (on b7 b6)
    (clear b1)
    (clear b9)
    (clear b11)
    (clear b10)
    (clear b8)
    (clear b2)
    (clear b7)
  )
  (:goal
    (and
      (on b2 b1)
    )
  )
)
