(define (problem instance-11)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10 b11)
  (:init
    (handempty)
    (ontable b11)
    (ontable b8)
    (ontable b10)
    (ontable b2)
    (ontable b6)
    (ontable b9)
    (ontable b4)
    (ontable b1)
    (on b5 b2)
    (on b7 b5)
    (on b3 b8)
    (clear b11)
    (clear b10)
    (clear b6)
    (clear b9)
    (clear b4)
    (clear b1)
    (clear b7)
    (clear b3)
  )
  (:goal
    (and
      (on b4 b3)
    )
  )
)
