(define (problem instance-10)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10)
  (:init
    (handempty)
    (ontable b4)
    (ontable b8)
    (ontable b2)
    (ontable b6)
    (ontable b9)
    (ontable b5)
    (on b3 b5)
    (on b10 b4)
    (on b1 b8)
    (on b7 b6)
    (clear b2)
    (clear b9)
    (clear b3)
    (clear b10)
    (clear b1)
    (clear b7)
  )
  (:goal
    (and
      (on b4 b7)
    )
  )
)
