(define (problem instance-11)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10 b11)
  (:init
    (handempty)
    (ontable b11)
    (ontable b10)
    (ontable b6)
    (ontable b5)
    (ontable b7)
    (ontable b2)
    (on b8 b2)
    (on b9 b6)
    (on b3 b9)
    (on b1 b10)
    (on b4 b1)
    (clear b11)
    (clear b5)
    (clear b7)
    (clear b8)
    (clear b3)
    (clear b4)
  )
  (:goal
    (and
      (on b2 b7)
    )
  )
)
