(define (problem instance-10)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10)
  (:init
    (handempty)
    (ontable b7)
    (ontable b9)
    (ontable b3)
    (ontable b6)
    (ontable b1)
    (on b2 b9)
    (on b4 b6)
    (on b8 b7)
    (on b5 b4)
    (on b10 b8)
    (clear b3)
    (clear b1)
    (clear b2)
    (clear b5)
    (clear b10)
  )
  (:goal
    (and
      (on b4 b10)
    )
  )
)
