(define (problem instance-9)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9)
  (:init
    (handempty)
    (ontable b6)
    (ontable b2)
    (ontable b8)
    (ontable b4)
    (ontable b5)
    (ontable b3)
    (ontable b9)
    (ontable b7)
    (ontable b1)
    (clear b6)
    (clear b2)
    (clear b8)
    (clear b4)
    (clear b5)
    (clear b3)
    (clear b9)
    (clear b7)
    (clear b1)
  )
  (:goal
    (and
      (on b9 b3)
    )
  )
)
