(define (problem instance-10)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10)
  (:init
    (handempty)
    (ontable b9)
    (ontable b2)
    (ontable b1)
    (ontable b4)
    (ontable b3)
    (ontable b7)
    (ontable b10)
    (on b5 b3)
    (on b8 b1)
    (on b6 b9)
    (clear b2)
    (clear b4)
    (clear b7)
    (clear b10)
    (clear b5)
    (clear b8)
    (clear b6)
  )
  (:goal
    (and
      (on b4 b1)
    )
  )
)
