(define (problem instance-9)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9)
  (:init
    (handempty)
    (ontable b7)
    (ontable b5)
    (ontable b1)
    (ontable b4)
    (ontable b3)
    (on b9 b4)
    (on b6 b9)
    (on b8 b5)
    (on b2 b7)
    (clear b1)
    (clear b3)
    (clear b6)
    (clear b8)
    (clear b2)
  )
  (:goal
    (and
      (on b9 b3)
    )
  )
)
