(define (problem instance-10)
  (:domain BLOCKS)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10)
  (:init
    (handempty)
    (ontable b7)
    (ontable b8)
    (ontable b6)
    (ontable b9)
    (on b3 b9)
    (on b10 b7)
    (on b5 b6)
    (on b2 b3)
    (on b4 b10)
    (on b1 b4)
    (clear b8)
    (clear b5)
    (clear b2)
    (clear b1)
  )
  (:goal
    (and
      (on b7 b3)
    )
  )
)
